-- ============================================
-- HEADZ HAIRSTYLE APP - COMPLETE DATABASE SETUP
-- ============================================
-- Run this entire script in Supabase Dashboard > SQL Editor
-- https://supabase.com/dashboard/project/YOUR_PROJECT/sql
-- ============================================

-- 1. USERS TABLE
-- Stores all user accounts (email, Google OAuth, etc.)
-- ============================================
CREATE TABLE IF NOT EXISTS public.users (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT,
  first_name TEXT,
  last_name TEXT,
  full_name TEXT,
  location TEXT,
  email_verified BOOLEAN DEFAULT false,
  is_admin BOOLEAN DEFAULT false,
  auth_provider TEXT DEFAULT 'email',
  supabase_user_id TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  last_login_at TIMESTAMP WITH TIME ZONE,
  -- Analytics tracking
  download_count INTEGER DEFAULT 0,
  share_count INTEGER DEFAULT 0,
  custom_prompt_count INTEGER DEFAULT 0,
  generation_count INTEGER DEFAULT 0,
  is_approved BOOLEAN DEFAULT false
);

-- Create index for faster email lookups
CREATE INDEX IF NOT EXISTS idx_users_email ON public.users(email);

-- 2. GENERATIONS TABLE
-- Stores all hairstyle generation records
-- ============================================
CREATE TABLE IF NOT EXISTS public.generations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  session_id TEXT,
  user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
  original_image_url TEXT,
  styled_image_url TEXT,
  generated_image_url TEXT,
  prompt TEXT,
  style_name TEXT,
  hairstyle_name TEXT,
  seed INTEGER,
  steps INTEGER,
  guidance_scale NUMERIC,
  strength NUMERIC,
  status TEXT DEFAULT 'completed',
  is_favorite BOOLEAN DEFAULT false,
  is_shared BOOLEAN DEFAULT false,
  metadata JSONB,
  gender TEXT
);

-- Add gender column if it doesn't exist (for existing installations)
ALTER TABLE public.generations ADD COLUMN IF NOT EXISTS gender TEXT;

-- Create indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_generations_user_id ON public.generations(user_id);
CREATE INDEX IF NOT EXISTS idx_generations_session_id ON public.generations(session_id);
CREATE INDEX IF NOT EXISTS idx_generations_created_at ON public.generations(created_at DESC);

-- 3. OTP_CODES TABLE
-- Stores one-time passwords for email verification
-- ============================================
CREATE TABLE IF NOT EXISTS public.otp_codes (
  email TEXT PRIMARY KEY,
  code TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- 4. STORAGE BUCKET
-- Create bucket for storing generated images
-- ============================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('generated-images', 'generated-images', true)
ON CONFLICT (id) DO NOTHING;

-- 5. STORAGE POLICIES
-- Allow public access to generated images bucket
-- ============================================

-- Policy: Allow anyone to view/download images
CREATE POLICY "Public Access" ON storage.objects
FOR SELECT
USING (bucket_id = 'generated-images');

-- Policy: Allow anyone to upload images
CREATE POLICY "Public Upload" ON storage.objects
FOR INSERT
WITH CHECK (bucket_id = 'generated-images');

-- 6. ROW LEVEL SECURITY (RLS)
-- Enable RLS on tables (optional but recommended)
-- ============================================

-- Enable RLS on users table
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Policy: Users can read their own data
CREATE POLICY "Users can view own profile" ON public.users
FOR SELECT
USING (true);

-- Policy: Users can update their own data
CREATE POLICY "Users can update own profile" ON public.users
FOR UPDATE
USING (true);

-- Policy: Anyone can insert (for registration)
CREATE POLICY "Anyone can register" ON public.users
FOR INSERT
WITH CHECK (true);

-- Policy: Allow deleting users (for admin reject)
CREATE POLICY "Allow delete users" ON public.users
FOR DELETE
USING (true);

-- Enable RLS on generations table
ALTER TABLE public.generations ENABLE ROW LEVEL SECURITY;

-- Policy: Public read for generations
CREATE POLICY "Public read generations" ON public.generations
FOR SELECT
USING (true);

-- Policy: Public insert for generations
CREATE POLICY "Public insert generations" ON public.generations
FOR INSERT
WITH CHECK (true);

-- Policy: Public delete for generations
CREATE POLICY "Users can delete own generations" ON public.generations
FOR DELETE
USING (true);

-- Enable RLS on otp_codes table
ALTER TABLE public.otp_codes ENABLE ROW LEVEL SECURITY;

-- Policy: Public access for OTP operations
CREATE POLICY "Public OTP access" ON public.otp_codes
FOR ALL
USING (true)
WITH CHECK (true);

-- 7. CREATE ADMIN USER (OPTIONAL)
-- Uncomment and modify to create an admin user
-- ============================================
-- INSERT INTO public.users (email, password_hash, first_name, last_name, full_name, is_admin, email_verified)
-- VALUES ('admin@example.com', 'your_hashed_password', 'Admin', 'User', 'Admin User', true, true);

-- ============================================
-- SETUP COMPLETE!
-- ============================================
--
-- Tables created:
--   - public.users
--   - public.generations
--   - public.otp_codes
--
-- Storage bucket created:
--   - generated-images (public)
--
-- Next steps:
--   1. Update your .env file with Supabase credentials
--   2. Configure Google OAuth in Supabase dashboard (if needed)
--   3. Test the application
-- ============================================
