-- Seed: 50+ active GitHub repos as Epics, with Stories and Tasks beneath each.
-- Run after migrations_devops_stage5.sql. Idempotent.
-- Project: bvaefzcsgtgqwftczixb

-- 1. Projects (categories)
insert into dev_projects (id, name, color) values
  ('p_healthcare', 'Healthcare HMS', '#2563eb'),
  ('p_compliance', 'Compliance & Audit', '#7c3aed'),
  ('p_scada', 'Industrial / SCADA', '#0ea5e9'),
  ('p_ai', 'AI Agents & Tooling', '#0e7490'),
  ('p_crm', 'CRM Platforms', '#047857'),
  ('p_sales', 'Sales & Outreach', '#ca8a04'),
  ('p_mobile_other', 'Mobile & Other', '#db2777') on conflict (id) do nothing;

-- 2. Epics, Stories, Tasks
with t as (select now() as ts)
insert into dev_work_items (id, project_id, parent_id, type, title, description, state, priority, points)
values
  ('epic_adamrit', 'p_healthcare', NULL, 'Epic', 'adamrit', 'GitHub: https://github.com/chatgptnotes/adamrit — Adamrit hospital management system', 'To Do', 'Medium', 21),
  ('story_adamrit_1', 'p_healthcare', 'epic_adamrit', 'Story', 'Patient registration & demographics', '', 'To Do', 'Medium', 5),
  ('task_adamrit_1_1', 'p_healthcare', 'story_adamrit_1', 'Task', 'DB schema for patients', '', 'To Do', 'Medium', 2),
  ('task_adamrit_1_2', 'p_healthcare', 'story_adamrit_1', 'Task', 'Registration UI', '', 'To Do', 'Medium', 2),
  ('story_adamrit_2', 'p_healthcare', 'epic_adamrit', 'Story', 'OPD / IPD workflow', '', 'To Do', 'Medium', 5),
  ('task_adamrit_2_1', 'p_healthcare', 'story_adamrit_2', 'Task', 'Visit creation API', '', 'To Do', 'Medium', 2),
  ('task_adamrit_2_2', 'p_healthcare', 'story_adamrit_2', 'Task', 'Doctor desk UI', '', 'To Do', 'Medium', 2),
  ('story_adamrit_3', 'p_healthcare', 'epic_adamrit', 'Story', 'Billing & insurance integration', '', 'To Do', 'Medium', 5),
  ('task_adamrit_3_1', 'p_healthcare', 'story_adamrit_3', 'Task', 'Tariff master', '', 'To Do', 'Medium', 2),
  ('task_adamrit_3_2', 'p_healthcare', 'story_adamrit_3', 'Task', 'Claim form export', '', 'To Do', 'Medium', 2),
  ('story_adamrit_4', 'p_healthcare', 'epic_adamrit', 'Story', 'NABH-grade audit trail', '', 'To Do', 'Medium', 5),
  ('task_adamrit_4_1', 'p_healthcare', 'story_adamrit_4', 'Task', 'Append-only history log', '', 'To Do', 'Medium', 2),
  ('epic_hopehospital_dashboard', 'p_healthcare', NULL, 'Epic', 'hopehospital-dashboard', 'GitHub: https://github.com/chatgptnotes/hopehospital-dashboard — Hope Hospital + Ayushman ops dashboard (fluxio.work)', 'To Do', 'Medium', 21),
  ('story_hopehospital_dashboard_1', 'p_healthcare', 'epic_hopehospital_dashboard', 'Story', 'Patient registration & demographics', '', 'To Do', 'Medium', 5),
  ('task_hopehospital_dashboard_1_1', 'p_healthcare', 'story_hopehospital_dashboard_1', 'Task', 'DB schema for patients', '', 'To Do', 'Medium', 2),
  ('task_hopehospital_dashboard_1_2', 'p_healthcare', 'story_hopehospital_dashboard_1', 'Task', 'Registration UI', '', 'To Do', 'Medium', 2),
  ('story_hopehospital_dashboard_2', 'p_healthcare', 'epic_hopehospital_dashboard', 'Story', 'OPD / IPD workflow', '', 'To Do', 'Medium', 5),
  ('task_hopehospital_dashboard_2_1', 'p_healthcare', 'story_hopehospital_dashboard_2', 'Task', 'Visit creation API', '', 'To Do', 'Medium', 2),
  ('task_hopehospital_dashboard_2_2', 'p_healthcare', 'story_hopehospital_dashboard_2', 'Task', 'Doctor desk UI', '', 'To Do', 'Medium', 2),
  ('story_hopehospital_dashboard_3', 'p_healthcare', 'epic_hopehospital_dashboard', 'Story', 'Billing & insurance integration', '', 'To Do', 'Medium', 5),
  ('task_hopehospital_dashboard_3_1', 'p_healthcare', 'story_hopehospital_dashboard_3', 'Task', 'Tariff master', '', 'To Do', 'Medium', 2),
  ('task_hopehospital_dashboard_3_2', 'p_healthcare', 'story_hopehospital_dashboard_3', 'Task', 'Claim form export', '', 'To Do', 'Medium', 2),
  ('story_hopehospital_dashboard_4', 'p_healthcare', 'epic_hopehospital_dashboard', 'Story', 'NABH-grade audit trail', '', 'To Do', 'Medium', 5),
  ('task_hopehospital_dashboard_4_1', 'p_healthcare', 'story_hopehospital_dashboard_4', 'Task', 'Append-only history log', '', 'To Do', 'Medium', 2),
  ('epic_hopehospital_com', 'p_healthcare', NULL, 'Epic', 'hopehospital.com', 'GitHub: https://github.com/chatgptnotes/hopehospital.com — Hope Hospital public site', 'To Do', 'Medium', 21),
  ('story_hopehospital_com_1', 'p_healthcare', 'epic_hopehospital_com', 'Story', 'Landing page', '', 'To Do', 'Medium', 5),
  ('task_hopehospital_com_1_1', 'p_healthcare', 'story_hopehospital_com_1', 'Task', 'Hero + capability sections', '', 'To Do', 'Medium', 2),
  ('story_hopehospital_com_2', 'p_healthcare', 'epic_hopehospital_com', 'Story', 'SEO & analytics', '', 'To Do', 'Medium', 5),
  ('task_hopehospital_com_2_1', 'p_healthcare', 'story_hopehospital_com_2', 'Task', 'Meta tags', '', 'To Do', 'Medium', 2),
  ('task_hopehospital_com_2_2', 'p_healthcare', 'story_hopehospital_com_2', 'Task', 'GA4 wiring', '', 'To Do', 'Medium', 2),
  ('story_hopehospital_com_3', 'p_healthcare', 'epic_hopehospital_com', 'Story', 'Contact / lead form', '', 'To Do', 'Medium', 5),
  ('task_hopehospital_com_3_1', 'p_healthcare', 'story_hopehospital_com_3', 'Task', 'Form submission handler', '', 'To Do', 'Medium', 2),
  ('epic_drmhope', 'p_healthcare', NULL, 'Epic', 'DrmHope', 'GitHub: https://github.com/chatgptnotes/DrmHope — DrM Hope HMS core', 'To Do', 'Medium', 21),
  ('story_drmhope_1', 'p_healthcare', 'epic_drmhope', 'Story', 'Patient registration & demographics', '', 'To Do', 'Medium', 5),
  ('task_drmhope_1_1', 'p_healthcare', 'story_drmhope_1', 'Task', 'DB schema for patients', '', 'To Do', 'Medium', 2),
  ('task_drmhope_1_2', 'p_healthcare', 'story_drmhope_1', 'Task', 'Registration UI', '', 'To Do', 'Medium', 2),
  ('story_drmhope_2', 'p_healthcare', 'epic_drmhope', 'Story', 'OPD / IPD workflow', '', 'To Do', 'Medium', 5),
  ('task_drmhope_2_1', 'p_healthcare', 'story_drmhope_2', 'Task', 'Visit creation API', '', 'To Do', 'Medium', 2),
  ('task_drmhope_2_2', 'p_healthcare', 'story_drmhope_2', 'Task', 'Doctor desk UI', '', 'To Do', 'Medium', 2),
  ('story_drmhope_3', 'p_healthcare', 'epic_drmhope', 'Story', 'Billing & insurance integration', '', 'To Do', 'Medium', 5),
  ('task_drmhope_3_1', 'p_healthcare', 'story_drmhope_3', 'Task', 'Tariff master', '', 'To Do', 'Medium', 2),
  ('task_drmhope_3_2', 'p_healthcare', 'story_drmhope_3', 'Task', 'Claim form export', '', 'To Do', 'Medium', 2),
  ('story_drmhope_4', 'p_healthcare', 'epic_drmhope', 'Story', 'NABH-grade audit trail', '', 'To Do', 'Medium', 5),
  ('task_drmhope_4_1', 'p_healthcare', 'story_drmhope_4', 'Task', 'Append-only history log', '', 'To Do', 'Medium', 2),
  ('epic_digihealthtwin', 'p_healthcare', NULL, 'Epic', 'Digihealthtwin', 'GitHub: https://github.com/chatgptnotes/Digihealthtwin — Diabetes health-twin app', 'To Do', 'Medium', 21),
  ('story_digihealthtwin_1', 'p_healthcare', 'epic_digihealthtwin', 'Story', 'Auth flow', '', 'To Do', 'Medium', 5),
  ('task_digihealthtwin_1_1', 'p_healthcare', 'story_digihealthtwin_1', 'Task', 'Login screen', '', 'To Do', 'Medium', 2),
  ('task_digihealthtwin_1_2', 'p_healthcare', 'story_digihealthtwin_1', 'Task', 'Token refresh', '', 'To Do', 'Medium', 2),
  ('story_digihealthtwin_2', 'p_healthcare', 'epic_digihealthtwin', 'Story', 'Offline support', '', 'To Do', 'Medium', 5),
  ('task_digihealthtwin_2_1', 'p_healthcare', 'story_digihealthtwin_2', 'Task', 'Local cache', '', 'To Do', 'Medium', 2),
  ('task_digihealthtwin_2_2', 'p_healthcare', 'story_digihealthtwin_2', 'Task', 'Sync queue', '', 'To Do', 'Medium', 2),
  ('story_digihealthtwin_3', 'p_healthcare', 'epic_digihealthtwin', 'Story', 'Push notifications', '', 'To Do', 'Medium', 5),
  ('task_digihealthtwin_3_1', 'p_healthcare', 'story_digihealthtwin_3', 'Task', 'FCM/APNs setup', '', 'To Do', 'Medium', 2),
  ('story_digihealthtwin_4', 'p_healthcare', 'epic_digihealthtwin', 'Story', 'App store packaging', '', 'To Do', 'Medium', 5),
  ('task_digihealthtwin_4_1', 'p_healthcare', 'story_digihealthtwin_4', 'Task', 'iOS build', '', 'To Do', 'Medium', 2),
  ('task_digihealthtwin_4_2', 'p_healthcare', 'story_digihealthtwin_4', 'Task', 'Android build', '', 'To Do', 'Medium', 2),
  ('epic_healthplus_mobile_app', 'p_healthcare', NULL, 'Epic', 'HealthPlus-mobile-app', 'GitHub: https://github.com/chatgptnotes/HealthPlus-mobile-app — HealthPlus patient mobile app', 'To Do', 'Medium', 21),
  ('story_healthplus_mobile_app_1', 'p_healthcare', 'epic_healthplus_mobile_app', 'Story', 'Auth flow', '', 'To Do', 'Medium', 5),
  ('task_healthplus_mobile_app_1_1', 'p_healthcare', 'story_healthplus_mobile_app_1', 'Task', 'Login screen', '', 'To Do', 'Medium', 2),
  ('task_healthplus_mobile_app_1_2', 'p_healthcare', 'story_healthplus_mobile_app_1', 'Task', 'Token refresh', '', 'To Do', 'Medium', 2),
  ('story_healthplus_mobile_app_2', 'p_healthcare', 'epic_healthplus_mobile_app', 'Story', 'Offline support', '', 'To Do', 'Medium', 5),
  ('task_healthplus_mobile_app_2_1', 'p_healthcare', 'story_healthplus_mobile_app_2', 'Task', 'Local cache', '', 'To Do', 'Medium', 2),
  ('task_healthplus_mobile_app_2_2', 'p_healthcare', 'story_healthplus_mobile_app_2', 'Task', 'Sync queue', '', 'To Do', 'Medium', 2),
  ('story_healthplus_mobile_app_3', 'p_healthcare', 'epic_healthplus_mobile_app', 'Story', 'Push notifications', '', 'To Do', 'Medium', 5),
  ('task_healthplus_mobile_app_3_1', 'p_healthcare', 'story_healthplus_mobile_app_3', 'Task', 'FCM/APNs setup', '', 'To Do', 'Medium', 2),
  ('story_healthplus_mobile_app_4', 'p_healthcare', 'epic_healthplus_mobile_app', 'Story', 'App store packaging', '', 'To Do', 'Medium', 5),
  ('task_healthplus_mobile_app_4_1', 'p_healthcare', 'story_healthplus_mobile_app_4', 'Task', 'iOS build', '', 'To Do', 'Medium', 2),
  ('task_healthplus_mobile_app_4_2', 'p_healthcare', 'story_healthplus_mobile_app_4', 'Task', 'Android build', '', 'To Do', 'Medium', 2),
  ('epic_vivahgmc_com', 'p_healthcare', NULL, 'Epic', 'vivahgmc.com', 'GitHub: https://github.com/chatgptnotes/vivahgmc.com — VivahGMC clinic site', 'To Do', 'Medium', 21),
  ('story_vivahgmc_com_1', 'p_healthcare', 'epic_vivahgmc_com', 'Story', 'Landing page', '', 'To Do', 'Medium', 5),
  ('task_vivahgmc_com_1_1', 'p_healthcare', 'story_vivahgmc_com_1', 'Task', 'Hero + capability sections', '', 'To Do', 'Medium', 2),
  ('story_vivahgmc_com_2', 'p_healthcare', 'epic_vivahgmc_com', 'Story', 'SEO & analytics', '', 'To Do', 'Medium', 5),
  ('task_vivahgmc_com_2_1', 'p_healthcare', 'story_vivahgmc_com_2', 'Task', 'Meta tags', '', 'To Do', 'Medium', 2),
  ('task_vivahgmc_com_2_2', 'p_healthcare', 'story_vivahgmc_com_2', 'Task', 'GA4 wiring', '', 'To Do', 'Medium', 2),
  ('story_vivahgmc_com_3', 'p_healthcare', 'epic_vivahgmc_com', 'Story', 'Contact / lead form', '', 'To Do', 'Medium', 5),
  ('task_vivahgmc_com_3_1', 'p_healthcare', 'story_vivahgmc_com_3', 'Task', 'Form submission handler', '', 'To Do', 'Medium', 2),
  ('epic_hospital_equipment_maintenance', 'p_healthcare', NULL, 'Epic', 'Hospital_Equipment_Maintenance', 'GitHub: https://github.com/chatgptnotes/Hospital_Equipment_Maintenance — Hospital equipment maintenance tracker', 'To Do', 'Medium', 21),
  ('story_hospital_equipment_maintenance_1', 'p_healthcare', 'epic_hospital_equipment_maintenance', 'Story', 'Document checklist & versioning', '', 'To Do', 'Medium', 5),
  ('task_hospital_equipment_maintenance_1_1', 'p_healthcare', 'story_hospital_equipment_maintenance_1', 'Task', 'Checklist schema', '', 'To Do', 'Medium', 2),
  ('task_hospital_equipment_maintenance_1_2', 'p_healthcare', 'story_hospital_equipment_maintenance_1', 'Task', 'Upload + version UI', '', 'To Do', 'Medium', 2),
  ('story_hospital_equipment_maintenance_2', 'p_healthcare', 'epic_hospital_equipment_maintenance', 'Story', 'Auto-generated audit report (PDF)', '', 'To Do', 'Medium', 5),
  ('task_hospital_equipment_maintenance_2_1', 'p_healthcare', 'story_hospital_equipment_maintenance_2', 'Task', 'Report template', '', 'To Do', 'Medium', 2),
  ('task_hospital_equipment_maintenance_2_2', 'p_healthcare', 'story_hospital_equipment_maintenance_2', 'Task', 'PDF render pipeline', '', 'To Do', 'Medium', 2),
  ('story_hospital_equipment_maintenance_3', 'p_healthcare', 'epic_hospital_equipment_maintenance', 'Story', 'User attestation & e-sign', '', 'To Do', 'Medium', 5),
  ('task_hospital_equipment_maintenance_3_1', 'p_healthcare', 'story_hospital_equipment_maintenance_3', 'Task', 'Attestation form', '', 'To Do', 'Medium', 2),
  ('task_hospital_equipment_maintenance_3_2', 'p_healthcare', 'story_hospital_equipment_maintenance_3', 'Task', 'Audit-trail capture', '', 'To Do', 'Medium', 2),
  ('epic_nabhonline', 'p_compliance', NULL, 'Epic', 'nabhonline', 'GitHub: https://github.com/chatgptnotes/nabhonline — NABH compliance SaaS', 'To Do', 'Medium', 21),
  ('story_nabhonline_1', 'p_compliance', 'epic_nabhonline', 'Story', 'Document checklist & versioning', '', 'To Do', 'Medium', 5),
  ('task_nabhonline_1_1', 'p_compliance', 'story_nabhonline_1', 'Task', 'Checklist schema', '', 'To Do', 'Medium', 2),
  ('task_nabhonline_1_2', 'p_compliance', 'story_nabhonline_1', 'Task', 'Upload + version UI', '', 'To Do', 'Medium', 2),
  ('story_nabhonline_2', 'p_compliance', 'epic_nabhonline', 'Story', 'Auto-generated audit report (PDF)', '', 'To Do', 'Medium', 5),
  ('task_nabhonline_2_1', 'p_compliance', 'story_nabhonline_2', 'Task', 'Report template', '', 'To Do', 'Medium', 2),
  ('task_nabhonline_2_2', 'p_compliance', 'story_nabhonline_2', 'Task', 'PDF render pipeline', '', 'To Do', 'Medium', 2),
  ('story_nabhonline_3', 'p_compliance', 'epic_nabhonline', 'Story', 'User attestation & e-sign', '', 'To Do', 'Medium', 5),
  ('task_nabhonline_3_1', 'p_compliance', 'story_nabhonline_3', 'Task', 'Attestation form', '', 'To Do', 'Medium', 2),
  ('task_nabhonline_3_2', 'p_compliance', 'story_nabhonline_3', 'Task', 'Audit-trail capture', '', 'To Do', 'Medium', 2),
  ('epic_nabh_compliance_report', 'p_compliance', NULL, 'Epic', 'nabh-compliance-report', 'GitHub: https://github.com/chatgptnotes/nabh-compliance-report — NABH audit report generator', 'To Do', 'Medium', 21),
  ('story_nabh_compliance_report_1', 'p_compliance', 'epic_nabh_compliance_report', 'Story', 'Document checklist & versioning', '', 'To Do', 'Medium', 5),
  ('task_nabh_compliance_report_1_1', 'p_compliance', 'story_nabh_compliance_report_1', 'Task', 'Checklist schema', '', 'To Do', 'Medium', 2),
  ('task_nabh_compliance_report_1_2', 'p_compliance', 'story_nabh_compliance_report_1', 'Task', 'Upload + version UI', '', 'To Do', 'Medium', 2),
  ('story_nabh_compliance_report_2', 'p_compliance', 'epic_nabh_compliance_report', 'Story', 'Auto-generated audit report (PDF)', '', 'To Do', 'Medium', 5),
  ('task_nabh_compliance_report_2_1', 'p_compliance', 'story_nabh_compliance_report_2', 'Task', 'Report template', '', 'To Do', 'Medium', 2),
  ('task_nabh_compliance_report_2_2', 'p_compliance', 'story_nabh_compliance_report_2', 'Task', 'PDF render pipeline', '', 'To Do', 'Medium', 2),
  ('story_nabh_compliance_report_3', 'p_compliance', 'epic_nabh_compliance_report', 'Story', 'User attestation & e-sign', '', 'To Do', 'Medium', 5),
  ('task_nabh_compliance_report_3_1', 'p_compliance', 'story_nabh_compliance_report_3', 'Task', 'Attestation form', '', 'To Do', 'Medium', 2),
  ('task_nabh_compliance_report_3_2', 'p_compliance', 'story_nabh_compliance_report_3', 'Task', 'Audit-trail capture', '', 'To Do', 'Medium', 2),
  ('epic_manikaran_dam_safety', 'p_compliance', NULL, 'Epic', 'manikaran-dam-safety', 'GitHub: https://github.com/chatgptnotes/manikaran-dam-safety — Dam Safety platform - Gosikhurd pilot', 'To Do', 'Medium', 21),
  ('story_manikaran_dam_safety_1', 'p_compliance', 'epic_manikaran_dam_safety', 'Story', 'Document checklist & versioning', '', 'To Do', 'Medium', 5),
  ('task_manikaran_dam_safety_1_1', 'p_compliance', 'story_manikaran_dam_safety_1', 'Task', 'Checklist schema', '', 'To Do', 'Medium', 2),
  ('task_manikaran_dam_safety_1_2', 'p_compliance', 'story_manikaran_dam_safety_1', 'Task', 'Upload + version UI', '', 'To Do', 'Medium', 2),
  ('story_manikaran_dam_safety_2', 'p_compliance', 'epic_manikaran_dam_safety', 'Story', 'Auto-generated audit report (PDF)', '', 'To Do', 'Medium', 5),
  ('task_manikaran_dam_safety_2_1', 'p_compliance', 'story_manikaran_dam_safety_2', 'Task', 'Report template', '', 'To Do', 'Medium', 2),
  ('task_manikaran_dam_safety_2_2', 'p_compliance', 'story_manikaran_dam_safety_2', 'Task', 'PDF render pipeline', '', 'To Do', 'Medium', 2),
  ('story_manikaran_dam_safety_3', 'p_compliance', 'epic_manikaran_dam_safety', 'Story', 'User attestation & e-sign', '', 'To Do', 'Medium', 5),
  ('task_manikaran_dam_safety_3_1', 'p_compliance', 'story_manikaran_dam_safety_3', 'Task', 'Attestation form', '', 'To Do', 'Medium', 2),
  ('task_manikaran_dam_safety_3_2', 'p_compliance', 'story_manikaran_dam_safety_3', 'Task', 'Audit-trail capture', '', 'To Do', 'Medium', 2),
  ('epic_pratyaya', 'p_compliance', NULL, 'Epic', 'pratyaya', 'GitHub: https://github.com/chatgptnotes/pratyaya — Compliance gateway for infrastructure drawings (Pune Metro)', 'To Do', 'Medium', 21),
  ('story_pratyaya_1', 'p_compliance', 'epic_pratyaya', 'Story', 'Document checklist & versioning', '', 'To Do', 'Medium', 5),
  ('task_pratyaya_1_1', 'p_compliance', 'story_pratyaya_1', 'Task', 'Checklist schema', '', 'To Do', 'Medium', 2),
  ('task_pratyaya_1_2', 'p_compliance', 'story_pratyaya_1', 'Task', 'Upload + version UI', '', 'To Do', 'Medium', 2),
  ('story_pratyaya_2', 'p_compliance', 'epic_pratyaya', 'Story', 'Auto-generated audit report (PDF)', '', 'To Do', 'Medium', 5),
  ('task_pratyaya_2_1', 'p_compliance', 'story_pratyaya_2', 'Task', 'Report template', '', 'To Do', 'Medium', 2),
  ('task_pratyaya_2_2', 'p_compliance', 'story_pratyaya_2', 'Task', 'PDF render pipeline', '', 'To Do', 'Medium', 2),
  ('story_pratyaya_3', 'p_compliance', 'epic_pratyaya', 'Story', 'User attestation & e-sign', '', 'To Do', 'Medium', 5),
  ('task_pratyaya_3_1', 'p_compliance', 'story_pratyaya_3', 'Task', 'Attestation form', '', 'To Do', 'Medium', 2),
  ('task_pratyaya_3_2', 'p_compliance', 'story_pratyaya_3', 'Task', 'Audit-trail capture', '', 'To Do', 'Medium', 2),
  ('epic_nexapulse', 'p_compliance', NULL, 'Epic', 'nexapulse', 'GitHub: https://github.com/chatgptnotes/nexapulse — Tender document audit framework (Pune Metro)', 'To Do', 'Medium', 21),
  ('story_nexapulse_1', 'p_compliance', 'epic_nexapulse', 'Story', 'Document checklist & versioning', '', 'To Do', 'Medium', 5),
  ('task_nexapulse_1_1', 'p_compliance', 'story_nexapulse_1', 'Task', 'Checklist schema', '', 'To Do', 'Medium', 2),
  ('task_nexapulse_1_2', 'p_compliance', 'story_nexapulse_1', 'Task', 'Upload + version UI', '', 'To Do', 'Medium', 2),
  ('story_nexapulse_2', 'p_compliance', 'epic_nexapulse', 'Story', 'Auto-generated audit report (PDF)', '', 'To Do', 'Medium', 5),
  ('task_nexapulse_2_1', 'p_compliance', 'story_nexapulse_2', 'Task', 'Report template', '', 'To Do', 'Medium', 2),
  ('task_nexapulse_2_2', 'p_compliance', 'story_nexapulse_2', 'Task', 'PDF render pipeline', '', 'To Do', 'Medium', 2),
  ('story_nexapulse_3', 'p_compliance', 'epic_nexapulse', 'Story', 'User attestation & e-sign', '', 'To Do', 'Medium', 5),
  ('task_nexapulse_3_1', 'p_compliance', 'story_nexapulse_3', 'Task', 'Attestation form', '', 'To Do', 'Medium', 2),
  ('task_nexapulse_3_2', 'p_compliance', 'story_nexapulse_3', 'Task', 'Audit-trail capture', '', 'To Do', 'Medium', 2),
  ('epic_hazpredict', 'p_compliance', NULL, 'Epic', 'HazPredict', 'GitHub: https://github.com/chatgptnotes/HazPredict — Predictive gas leak detection for thermal plants', 'To Do', 'Medium', 21),
  ('story_hazpredict_1', 'p_compliance', 'epic_hazpredict', 'Story', 'PLC / device protocol adapters', '', 'To Do', 'Medium', 5),
  ('task_hazpredict_1_1', 'p_compliance', 'story_hazpredict_1', 'Task', 'Modbus TCP driver', '', 'To Do', 'Medium', 2),
  ('task_hazpredict_1_2', 'p_compliance', 'story_hazpredict_1', 'Task', 'OPC-UA driver', '', 'To Do', 'Medium', 2),
  ('story_hazpredict_2', 'p_compliance', 'epic_hazpredict', 'Story', 'Real-time tag dashboard', '', 'To Do', 'Medium', 5),
  ('task_hazpredict_2_1', 'p_compliance', 'story_hazpredict_2', 'Task', 'Socket.IO tag stream', '', 'To Do', 'Medium', 2),
  ('task_hazpredict_2_2', 'p_compliance', 'story_hazpredict_2', 'Task', 'ReactFlow HMI canvas', '', 'To Do', 'Medium', 2),
  ('story_hazpredict_3', 'p_compliance', 'epic_hazpredict', 'Story', 'Alarm engine & escalation', '', 'To Do', 'Medium', 5),
  ('task_hazpredict_3_1', 'p_compliance', 'story_hazpredict_3', 'Task', 'Threshold rule engine', '', 'To Do', 'Medium', 2),
  ('task_hazpredict_3_2', 'p_compliance', 'story_hazpredict_3', 'Task', 'WhatsApp / email channel', '', 'To Do', 'Medium', 2),
  ('story_hazpredict_4', 'p_compliance', 'epic_hazpredict', 'Story', 'Historical trends & reports', '', 'To Do', 'Medium', 5),
  ('task_hazpredict_4_1', 'p_compliance', 'story_hazpredict_4', 'Task', 'Time-series query API', '', 'To Do', 'Medium', 2),
  ('task_hazpredict_4_2', 'p_compliance', 'story_hazpredict_4', 'Task', 'Trend chart UI', '', 'To Do', 'Medium', 2),
  ('epic_plcautopilot_com', 'p_scada', NULL, 'Epic', 'plcautopilot.com', 'GitHub: https://github.com/chatgptnotes/plcautopilot.com — PLC programming assistant', 'To Do', 'Medium', 21),
  ('story_plcautopilot_com_1', 'p_scada', 'epic_plcautopilot_com', 'Story', 'PLC / device protocol adapters', '', 'To Do', 'Medium', 5),
  ('task_plcautopilot_com_1_1', 'p_scada', 'story_plcautopilot_com_1', 'Task', 'Modbus TCP driver', '', 'To Do', 'Medium', 2),
  ('task_plcautopilot_com_1_2', 'p_scada', 'story_plcautopilot_com_1', 'Task', 'OPC-UA driver', '', 'To Do', 'Medium', 2),
  ('story_plcautopilot_com_2', 'p_scada', 'epic_plcautopilot_com', 'Story', 'Real-time tag dashboard', '', 'To Do', 'Medium', 5),
  ('task_plcautopilot_com_2_1', 'p_scada', 'story_plcautopilot_com_2', 'Task', 'Socket.IO tag stream', '', 'To Do', 'Medium', 2),
  ('task_plcautopilot_com_2_2', 'p_scada', 'story_plcautopilot_com_2', 'Task', 'ReactFlow HMI canvas', '', 'To Do', 'Medium', 2),
  ('story_plcautopilot_com_3', 'p_scada', 'epic_plcautopilot_com', 'Story', 'Alarm engine & escalation', '', 'To Do', 'Medium', 5),
  ('task_plcautopilot_com_3_1', 'p_scada', 'story_plcautopilot_com_3', 'Task', 'Threshold rule engine', '', 'To Do', 'Medium', 2),
  ('task_plcautopilot_com_3_2', 'p_scada', 'story_plcautopilot_com_3', 'Task', 'WhatsApp / email channel', '', 'To Do', 'Medium', 2),
  ('story_plcautopilot_com_4', 'p_scada', 'epic_plcautopilot_com', 'Story', 'Historical trends & reports', '', 'To Do', 'Medium', 5),
  ('task_plcautopilot_com_4_1', 'p_scada', 'story_plcautopilot_com_4', 'Task', 'Time-series query API', '', 'To Do', 'Medium', 2),
  ('task_plcautopilot_com_4_2', 'p_scada', 'story_plcautopilot_com_4', 'Task', 'Trend chart UI', '', 'To Do', 'Medium', 2),
  ('epic_ecologic_plc_assistant', 'p_scada', NULL, 'Epic', 'EcoLogic-PLC-Assistant', 'GitHub: https://github.com/chatgptnotes/EcoLogic-PLC-Assistant — EcoLogic PLC code generator', 'To Do', 'Medium', 21),
  ('story_ecologic_plc_assistant_1', 'p_scada', 'epic_ecologic_plc_assistant', 'Story', 'PLC / device protocol adapters', '', 'To Do', 'Medium', 5),
  ('task_ecologic_plc_assistant_1_1', 'p_scada', 'story_ecologic_plc_assistant_1', 'Task', 'Modbus TCP driver', '', 'To Do', 'Medium', 2),
  ('task_ecologic_plc_assistant_1_2', 'p_scada', 'story_ecologic_plc_assistant_1', 'Task', 'OPC-UA driver', '', 'To Do', 'Medium', 2),
  ('story_ecologic_plc_assistant_2', 'p_scada', 'epic_ecologic_plc_assistant', 'Story', 'Real-time tag dashboard', '', 'To Do', 'Medium', 5),
  ('task_ecologic_plc_assistant_2_1', 'p_scada', 'story_ecologic_plc_assistant_2', 'Task', 'Socket.IO tag stream', '', 'To Do', 'Medium', 2),
  ('task_ecologic_plc_assistant_2_2', 'p_scada', 'story_ecologic_plc_assistant_2', 'Task', 'ReactFlow HMI canvas', '', 'To Do', 'Medium', 2),
  ('story_ecologic_plc_assistant_3', 'p_scada', 'epic_ecologic_plc_assistant', 'Story', 'Alarm engine & escalation', '', 'To Do', 'Medium', 5),
  ('task_ecologic_plc_assistant_3_1', 'p_scada', 'story_ecologic_plc_assistant_3', 'Task', 'Threshold rule engine', '', 'To Do', 'Medium', 2),
  ('task_ecologic_plc_assistant_3_2', 'p_scada', 'story_ecologic_plc_assistant_3', 'Task', 'WhatsApp / email channel', '', 'To Do', 'Medium', 2),
  ('story_ecologic_plc_assistant_4', 'p_scada', 'epic_ecologic_plc_assistant', 'Story', 'Historical trends & reports', '', 'To Do', 'Medium', 5),
  ('task_ecologic_plc_assistant_4_1', 'p_scada', 'story_ecologic_plc_assistant_4', 'Task', 'Time-series query API', '', 'To Do', 'Medium', 2),
  ('task_ecologic_plc_assistant_4_2', 'p_scada', 'story_ecologic_plc_assistant_4', 'Task', 'Trend chart UI', '', 'To Do', 'Medium', 2),
  ('epic_scada_work', 'p_scada', NULL, 'Epic', 'scada.work', 'GitHub: https://github.com/chatgptnotes/scada.work — SCADA HMI platform', 'To Do', 'Medium', 21),
  ('story_scada_work_1', 'p_scada', 'epic_scada_work', 'Story', 'PLC / device protocol adapters', '', 'To Do', 'Medium', 5),
  ('task_scada_work_1_1', 'p_scada', 'story_scada_work_1', 'Task', 'Modbus TCP driver', '', 'To Do', 'Medium', 2),
  ('task_scada_work_1_2', 'p_scada', 'story_scada_work_1', 'Task', 'OPC-UA driver', '', 'To Do', 'Medium', 2),
  ('story_scada_work_2', 'p_scada', 'epic_scada_work', 'Story', 'Real-time tag dashboard', '', 'To Do', 'Medium', 5),
  ('task_scada_work_2_1', 'p_scada', 'story_scada_work_2', 'Task', 'Socket.IO tag stream', '', 'To Do', 'Medium', 2),
  ('task_scada_work_2_2', 'p_scada', 'story_scada_work_2', 'Task', 'ReactFlow HMI canvas', '', 'To Do', 'Medium', 2),
  ('story_scada_work_3', 'p_scada', 'epic_scada_work', 'Story', 'Alarm engine & escalation', '', 'To Do', 'Medium', 5),
  ('task_scada_work_3_1', 'p_scada', 'story_scada_work_3', 'Task', 'Threshold rule engine', '', 'To Do', 'Medium', 2),
  ('task_scada_work_3_2', 'p_scada', 'story_scada_work_3', 'Task', 'WhatsApp / email channel', '', 'To Do', 'Medium', 2),
  ('story_scada_work_4', 'p_scada', 'epic_scada_work', 'Story', 'Historical trends & reports', '', 'To Do', 'Medium', 5),
  ('task_scada_work_4_1', 'p_scada', 'story_scada_work_4', 'Task', 'Time-series query API', '', 'To Do', 'Medium', 2),
  ('task_scada_work_4_2', 'p_scada', 'story_scada_work_4', 'Task', 'Trend chart UI', '', 'To Do', 'Medium', 2),
  ('epic_gridvision_scada', 'p_scada', NULL, 'Epic', 'gridvision-scada', 'GitHub: https://github.com/chatgptnotes/gridvision-scada — MSEDCL smart distribution SCADA', 'To Do', 'Medium', 21),
  ('story_gridvision_scada_1', 'p_scada', 'epic_gridvision_scada', 'Story', 'PLC / device protocol adapters', '', 'To Do', 'Medium', 5),
  ('task_gridvision_scada_1_1', 'p_scada', 'story_gridvision_scada_1', 'Task', 'Modbus TCP driver', '', 'To Do', 'Medium', 2),
  ('task_gridvision_scada_1_2', 'p_scada', 'story_gridvision_scada_1', 'Task', 'OPC-UA driver', '', 'To Do', 'Medium', 2),
  ('story_gridvision_scada_2', 'p_scada', 'epic_gridvision_scada', 'Story', 'Real-time tag dashboard', '', 'To Do', 'Medium', 5),
  ('task_gridvision_scada_2_1', 'p_scada', 'story_gridvision_scada_2', 'Task', 'Socket.IO tag stream', '', 'To Do', 'Medium', 2),
  ('task_gridvision_scada_2_2', 'p_scada', 'story_gridvision_scada_2', 'Task', 'ReactFlow HMI canvas', '', 'To Do', 'Medium', 2),
  ('story_gridvision_scada_3', 'p_scada', 'epic_gridvision_scada', 'Story', 'Alarm engine & escalation', '', 'To Do', 'Medium', 5),
  ('task_gridvision_scada_3_1', 'p_scada', 'story_gridvision_scada_3', 'Task', 'Threshold rule engine', '', 'To Do', 'Medium', 2),
  ('task_gridvision_scada_3_2', 'p_scada', 'story_gridvision_scada_3', 'Task', 'WhatsApp / email channel', '', 'To Do', 'Medium', 2),
  ('story_gridvision_scada_4', 'p_scada', 'epic_gridvision_scada', 'Story', 'Historical trends & reports', '', 'To Do', 'Medium', 5),
  ('task_gridvision_scada_4_1', 'p_scada', 'story_gridvision_scada_4', 'Task', 'Time-series query API', '', 'To Do', 'Medium', 2),
  ('task_gridvision_scada_4_2', 'p_scada', 'story_gridvision_scada_4', 'Task', 'Trend chart UI', '', 'To Do', 'Medium', 2),
  ('epic_factorypulse_site', 'p_scada', NULL, 'Epic', 'factorypulse.site', 'GitHub: https://github.com/chatgptnotes/factorypulse.site — Factory production dashboard', 'To Do', 'Medium', 21),
  ('story_factorypulse_site_1', 'p_scada', 'epic_factorypulse_site', 'Story', 'PLC / device protocol adapters', '', 'To Do', 'Medium', 5),
  ('task_factorypulse_site_1_1', 'p_scada', 'story_factorypulse_site_1', 'Task', 'Modbus TCP driver', '', 'To Do', 'Medium', 2),
  ('task_factorypulse_site_1_2', 'p_scada', 'story_factorypulse_site_1', 'Task', 'OPC-UA driver', '', 'To Do', 'Medium', 2),
  ('story_factorypulse_site_2', 'p_scada', 'epic_factorypulse_site', 'Story', 'Real-time tag dashboard', '', 'To Do', 'Medium', 5),
  ('task_factorypulse_site_2_1', 'p_scada', 'story_factorypulse_site_2', 'Task', 'Socket.IO tag stream', '', 'To Do', 'Medium', 2),
  ('task_factorypulse_site_2_2', 'p_scada', 'story_factorypulse_site_2', 'Task', 'ReactFlow HMI canvas', '', 'To Do', 'Medium', 2),
  ('story_factorypulse_site_3', 'p_scada', 'epic_factorypulse_site', 'Story', 'Alarm engine & escalation', '', 'To Do', 'Medium', 5),
  ('task_factorypulse_site_3_1', 'p_scada', 'story_factorypulse_site_3', 'Task', 'Threshold rule engine', '', 'To Do', 'Medium', 2),
  ('task_factorypulse_site_3_2', 'p_scada', 'story_factorypulse_site_3', 'Task', 'WhatsApp / email channel', '', 'To Do', 'Medium', 2),
  ('story_factorypulse_site_4', 'p_scada', 'epic_factorypulse_site', 'Story', 'Historical trends & reports', '', 'To Do', 'Medium', 5),
  ('task_factorypulse_site_4_1', 'p_scada', 'story_factorypulse_site_4', 'Task', 'Time-series query API', '', 'To Do', 'Medium', 2),
  ('task_factorypulse_site_4_2', 'p_scada', 'story_factorypulse_site_4', 'Task', 'Trend chart UI', '', 'To Do', 'Medium', 2),
  ('epic_ampris', 'p_scada', NULL, 'Epic', 'ampris', 'GitHub: https://github.com/chatgptnotes/ampris — Ampris power-system SCADA', 'To Do', 'Medium', 21),
  ('story_ampris_1', 'p_scada', 'epic_ampris', 'Story', 'PLC / device protocol adapters', '', 'To Do', 'Medium', 5),
  ('task_ampris_1_1', 'p_scada', 'story_ampris_1', 'Task', 'Modbus TCP driver', '', 'To Do', 'Medium', 2),
  ('task_ampris_1_2', 'p_scada', 'story_ampris_1', 'Task', 'OPC-UA driver', '', 'To Do', 'Medium', 2),
  ('story_ampris_2', 'p_scada', 'epic_ampris', 'Story', 'Real-time tag dashboard', '', 'To Do', 'Medium', 5),
  ('task_ampris_2_1', 'p_scada', 'story_ampris_2', 'Task', 'Socket.IO tag stream', '', 'To Do', 'Medium', 2),
  ('task_ampris_2_2', 'p_scada', 'story_ampris_2', 'Task', 'ReactFlow HMI canvas', '', 'To Do', 'Medium', 2),
  ('story_ampris_3', 'p_scada', 'epic_ampris', 'Story', 'Alarm engine & escalation', '', 'To Do', 'Medium', 5),
  ('task_ampris_3_1', 'p_scada', 'story_ampris_3', 'Task', 'Threshold rule engine', '', 'To Do', 'Medium', 2),
  ('task_ampris_3_2', 'p_scada', 'story_ampris_3', 'Task', 'WhatsApp / email channel', '', 'To Do', 'Medium', 2),
  ('story_ampris_4', 'p_scada', 'epic_ampris', 'Story', 'Historical trends & reports', '', 'To Do', 'Medium', 5),
  ('task_ampris_4_1', 'p_scada', 'story_ampris_4', 'Task', 'Time-series query API', '', 'To Do', 'Medium', 2),
  ('task_ampris_4_2', 'p_scada', 'story_ampris_4', 'Task', 'Trend chart UI', '', 'To Do', 'Medium', 2),
  ('epic_nexaproc', 'p_scada', NULL, 'Epic', 'nexaproc', 'GitHub: https://github.com/chatgptnotes/nexaproc — NexaProc factory automation platform', 'To Do', 'Medium', 21),
  ('story_nexaproc_1', 'p_scada', 'epic_nexaproc', 'Story', 'PLC / device protocol adapters', '', 'To Do', 'Medium', 5),
  ('task_nexaproc_1_1', 'p_scada', 'story_nexaproc_1', 'Task', 'Modbus TCP driver', '', 'To Do', 'Medium', 2),
  ('task_nexaproc_1_2', 'p_scada', 'story_nexaproc_1', 'Task', 'OPC-UA driver', '', 'To Do', 'Medium', 2),
  ('story_nexaproc_2', 'p_scada', 'epic_nexaproc', 'Story', 'Real-time tag dashboard', '', 'To Do', 'Medium', 5),
  ('task_nexaproc_2_1', 'p_scada', 'story_nexaproc_2', 'Task', 'Socket.IO tag stream', '', 'To Do', 'Medium', 2),
  ('task_nexaproc_2_2', 'p_scada', 'story_nexaproc_2', 'Task', 'ReactFlow HMI canvas', '', 'To Do', 'Medium', 2),
  ('story_nexaproc_3', 'p_scada', 'epic_nexaproc', 'Story', 'Alarm engine & escalation', '', 'To Do', 'Medium', 5),
  ('task_nexaproc_3_1', 'p_scada', 'story_nexaproc_3', 'Task', 'Threshold rule engine', '', 'To Do', 'Medium', 2),
  ('task_nexaproc_3_2', 'p_scada', 'story_nexaproc_3', 'Task', 'WhatsApp / email channel', '', 'To Do', 'Medium', 2),
  ('story_nexaproc_4', 'p_scada', 'epic_nexaproc', 'Story', 'Historical trends & reports', '', 'To Do', 'Medium', 5),
  ('task_nexaproc_4_1', 'p_scada', 'story_nexaproc_4', 'Task', 'Time-series query API', '', 'To Do', 'Medium', 2),
  ('task_nexaproc_4_2', 'p_scada', 'story_nexaproc_4', 'Task', 'Trend chart UI', '', 'To Do', 'Medium', 2),
  ('epic_autopaneldesign_com', 'p_scada', NULL, 'Epic', 'autopaneldesign.com', 'GitHub: https://github.com/chatgptnotes/autopaneldesign.com — Electrical panel auto-design', 'To Do', 'Medium', 21),
  ('story_autopaneldesign_com_1', 'p_scada', 'epic_autopaneldesign_com', 'Story', 'PLC / device protocol adapters', '', 'To Do', 'Medium', 5),
  ('task_autopaneldesign_com_1_1', 'p_scada', 'story_autopaneldesign_com_1', 'Task', 'Modbus TCP driver', '', 'To Do', 'Medium', 2),
  ('task_autopaneldesign_com_1_2', 'p_scada', 'story_autopaneldesign_com_1', 'Task', 'OPC-UA driver', '', 'To Do', 'Medium', 2),
  ('story_autopaneldesign_com_2', 'p_scada', 'epic_autopaneldesign_com', 'Story', 'Real-time tag dashboard', '', 'To Do', 'Medium', 5),
  ('task_autopaneldesign_com_2_1', 'p_scada', 'story_autopaneldesign_com_2', 'Task', 'Socket.IO tag stream', '', 'To Do', 'Medium', 2),
  ('task_autopaneldesign_com_2_2', 'p_scada', 'story_autopaneldesign_com_2', 'Task', 'ReactFlow HMI canvas', '', 'To Do', 'Medium', 2),
  ('story_autopaneldesign_com_3', 'p_scada', 'epic_autopaneldesign_com', 'Story', 'Alarm engine & escalation', '', 'To Do', 'Medium', 5),
  ('task_autopaneldesign_com_3_1', 'p_scada', 'story_autopaneldesign_com_3', 'Task', 'Threshold rule engine', '', 'To Do', 'Medium', 2),
  ('task_autopaneldesign_com_3_2', 'p_scada', 'story_autopaneldesign_com_3', 'Task', 'WhatsApp / email channel', '', 'To Do', 'Medium', 2),
  ('story_autopaneldesign_com_4', 'p_scada', 'epic_autopaneldesign_com', 'Story', 'Historical trends & reports', '', 'To Do', 'Medium', 5),
  ('task_autopaneldesign_com_4_1', 'p_scada', 'story_autopaneldesign_com_4', 'Task', 'Time-series query API', '', 'To Do', 'Medium', 2),
  ('task_autopaneldesign_com_4_2', 'p_scada', 'story_autopaneldesign_com_4', 'Task', 'Trend chart UI', '', 'To Do', 'Medium', 2),
  ('epic_flownexus', 'p_scada', NULL, 'Epic', 'flownexus', 'GitHub: https://github.com/chatgptnotes/flownexus — FlowNexus flow-monitoring platform', 'To Do', 'Medium', 21),
  ('story_flownexus_1', 'p_scada', 'epic_flownexus', 'Story', 'PLC / device protocol adapters', '', 'To Do', 'Medium', 5),
  ('task_flownexus_1_1', 'p_scada', 'story_flownexus_1', 'Task', 'Modbus TCP driver', '', 'To Do', 'Medium', 2),
  ('task_flownexus_1_2', 'p_scada', 'story_flownexus_1', 'Task', 'OPC-UA driver', '', 'To Do', 'Medium', 2),
  ('story_flownexus_2', 'p_scada', 'epic_flownexus', 'Story', 'Real-time tag dashboard', '', 'To Do', 'Medium', 5),
  ('task_flownexus_2_1', 'p_scada', 'story_flownexus_2', 'Task', 'Socket.IO tag stream', '', 'To Do', 'Medium', 2),
  ('task_flownexus_2_2', 'p_scada', 'story_flownexus_2', 'Task', 'ReactFlow HMI canvas', '', 'To Do', 'Medium', 2),
  ('story_flownexus_3', 'p_scada', 'epic_flownexus', 'Story', 'Alarm engine & escalation', '', 'To Do', 'Medium', 5),
  ('task_flownexus_3_1', 'p_scada', 'story_flownexus_3', 'Task', 'Threshold rule engine', '', 'To Do', 'Medium', 2),
  ('task_flownexus_3_2', 'p_scada', 'story_flownexus_3', 'Task', 'WhatsApp / email channel', '', 'To Do', 'Medium', 2),
  ('story_flownexus_4', 'p_scada', 'epic_flownexus', 'Story', 'Historical trends & reports', '', 'To Do', 'Medium', 5),
  ('task_flownexus_4_1', 'p_scada', 'story_flownexus_4', 'Task', 'Time-series query API', '', 'To Do', 'Medium', 2),
  ('task_flownexus_4_2', 'p_scada', 'story_flownexus_4', 'Task', 'Trend chart UI', '', 'To Do', 'Medium', 2),
  ('epic_galvon', 'p_scada', NULL, 'Epic', 'galvon', 'GitHub: https://github.com/chatgptnotes/galvon — Galvon industrial intelligence umbrella', 'To Do', 'Medium', 21),
  ('story_galvon_1', 'p_scada', 'epic_galvon', 'Story', 'Landing page', '', 'To Do', 'Medium', 5),
  ('task_galvon_1_1', 'p_scada', 'story_galvon_1', 'Task', 'Hero + capability sections', '', 'To Do', 'Medium', 2),
  ('story_galvon_2', 'p_scada', 'epic_galvon', 'Story', 'SEO & analytics', '', 'To Do', 'Medium', 5),
  ('task_galvon_2_1', 'p_scada', 'story_galvon_2', 'Task', 'Meta tags', '', 'To Do', 'Medium', 2),
  ('task_galvon_2_2', 'p_scada', 'story_galvon_2', 'Task', 'GA4 wiring', '', 'To Do', 'Medium', 2),
  ('story_galvon_3', 'p_scada', 'epic_galvon', 'Story', 'Contact / lead form', '', 'To Do', 'Medium', 5),
  ('task_galvon_3_1', 'p_scada', 'story_galvon_3', 'Task', 'Form submission handler', '', 'To Do', 'Medium', 2),
  ('epic_spare_part_optimizer', 'p_scada', NULL, 'Epic', 'Spare_part_Optimizer', 'GitHub: https://github.com/chatgptnotes/Spare_part_Optimizer — Industrial spare-part optimisation', 'To Do', 'Medium', 21),
  ('story_spare_part_optimizer_1', 'p_scada', 'epic_spare_part_optimizer', 'Story', 'PLC / device protocol adapters', '', 'To Do', 'Medium', 5),
  ('task_spare_part_optimizer_1_1', 'p_scada', 'story_spare_part_optimizer_1', 'Task', 'Modbus TCP driver', '', 'To Do', 'Medium', 2),
  ('task_spare_part_optimizer_1_2', 'p_scada', 'story_spare_part_optimizer_1', 'Task', 'OPC-UA driver', '', 'To Do', 'Medium', 2),
  ('story_spare_part_optimizer_2', 'p_scada', 'epic_spare_part_optimizer', 'Story', 'Real-time tag dashboard', '', 'To Do', 'Medium', 5),
  ('task_spare_part_optimizer_2_1', 'p_scada', 'story_spare_part_optimizer_2', 'Task', 'Socket.IO tag stream', '', 'To Do', 'Medium', 2),
  ('task_spare_part_optimizer_2_2', 'p_scada', 'story_spare_part_optimizer_2', 'Task', 'ReactFlow HMI canvas', '', 'To Do', 'Medium', 2),
  ('story_spare_part_optimizer_3', 'p_scada', 'epic_spare_part_optimizer', 'Story', 'Alarm engine & escalation', '', 'To Do', 'Medium', 5),
  ('task_spare_part_optimizer_3_1', 'p_scada', 'story_spare_part_optimizer_3', 'Task', 'Threshold rule engine', '', 'To Do', 'Medium', 2),
  ('task_spare_part_optimizer_3_2', 'p_scada', 'story_spare_part_optimizer_3', 'Task', 'WhatsApp / email channel', '', 'To Do', 'Medium', 2),
  ('story_spare_part_optimizer_4', 'p_scada', 'epic_spare_part_optimizer', 'Story', 'Historical trends & reports', '', 'To Do', 'Medium', 5),
  ('task_spare_part_optimizer_4_1', 'p_scada', 'story_spare_part_optimizer_4', 'Task', 'Time-series query API', '', 'To Do', 'Medium', 2),
  ('task_spare_part_optimizer_4_2', 'p_scada', 'story_spare_part_optimizer_4', 'Task', 'Trend chart UI', '', 'To Do', 'Medium', 2),
  ('epic_aiinmail_com', 'p_ai', NULL, 'Epic', 'aiinmail.com', 'GitHub: https://github.com/chatgptnotes/aiinmail.com — AI in Mail - executive inbox agent', 'To Do', 'Medium', 21),
  ('story_aiinmail_com_1', 'p_ai', 'epic_aiinmail_com', 'Story', 'LLM provider integration', '', 'To Do', 'Medium', 5),
  ('task_aiinmail_com_1_1', 'p_ai', 'story_aiinmail_com_1', 'Task', 'Anthropic + DeepSeek dual provider', '', 'To Do', 'Medium', 2),
  ('task_aiinmail_com_1_2', 'p_ai', 'story_aiinmail_com_1', 'Task', 'Cost monitoring', '', 'To Do', 'Medium', 2),
  ('story_aiinmail_com_2', 'p_ai', 'epic_aiinmail_com', 'Story', 'Prompt design & guardrails', '', 'To Do', 'Medium', 5),
  ('task_aiinmail_com_2_1', 'p_ai', 'story_aiinmail_com_2', 'Task', 'System prompt', '', 'To Do', 'Medium', 2),
  ('task_aiinmail_com_2_2', 'p_ai', 'story_aiinmail_com_2', 'Task', 'Output moderation', '', 'To Do', 'Medium', 2),
  ('story_aiinmail_com_3', 'p_ai', 'epic_aiinmail_com', 'Story', 'Workflow orchestration', '', 'To Do', 'Medium', 5),
  ('task_aiinmail_com_3_1', 'p_ai', 'story_aiinmail_com_3', 'Task', 'Job queue', '', 'To Do', 'Medium', 2),
  ('task_aiinmail_com_3_2', 'p_ai', 'story_aiinmail_com_3', 'Task', 'Retry policy', '', 'To Do', 'Medium', 2),
  ('epic_aidoccall_com', 'p_ai', NULL, 'Epic', 'aidoccall.com', 'GitHub: https://github.com/chatgptnotes/aidoccall.com — AI Doc Call voice agent', 'To Do', 'Medium', 21),
  ('story_aidoccall_com_1', 'p_ai', 'epic_aidoccall_com', 'Story', 'LLM provider integration', '', 'To Do', 'Medium', 5),
  ('task_aidoccall_com_1_1', 'p_ai', 'story_aidoccall_com_1', 'Task', 'Anthropic + DeepSeek dual provider', '', 'To Do', 'Medium', 2),
  ('task_aidoccall_com_1_2', 'p_ai', 'story_aidoccall_com_1', 'Task', 'Cost monitoring', '', 'To Do', 'Medium', 2),
  ('story_aidoccall_com_2', 'p_ai', 'epic_aidoccall_com', 'Story', 'Prompt design & guardrails', '', 'To Do', 'Medium', 5),
  ('task_aidoccall_com_2_1', 'p_ai', 'story_aidoccall_com_2', 'Task', 'System prompt', '', 'To Do', 'Medium', 2),
  ('task_aidoccall_com_2_2', 'p_ai', 'story_aidoccall_com_2', 'Task', 'Output moderation', '', 'To Do', 'Medium', 2),
  ('story_aidoccall_com_3', 'p_ai', 'epic_aidoccall_com', 'Story', 'Workflow orchestration', '', 'To Do', 'Medium', 5),
  ('task_aidoccall_com_3_1', 'p_ai', 'story_aidoccall_com_3', 'Task', 'Job queue', '', 'To Do', 'Medium', 2),
  ('task_aidoccall_com_3_2', 'p_ai', 'story_aidoccall_com_3', 'Task', 'Retry policy', '', 'To Do', 'Medium', 2),
  ('epic_aisurgeonpilot', 'p_ai', NULL, 'Epic', 'AiSurgeonPilot', 'GitHub: https://github.com/chatgptnotes/AiSurgeonPilot — AI Surgeon pilot', 'To Do', 'Medium', 21),
  ('story_aisurgeonpilot_1', 'p_ai', 'epic_aisurgeonpilot', 'Story', 'LLM provider integration', '', 'To Do', 'Medium', 5),
  ('task_aisurgeonpilot_1_1', 'p_ai', 'story_aisurgeonpilot_1', 'Task', 'Anthropic + DeepSeek dual provider', '', 'To Do', 'Medium', 2),
  ('task_aisurgeonpilot_1_2', 'p_ai', 'story_aisurgeonpilot_1', 'Task', 'Cost monitoring', '', 'To Do', 'Medium', 2),
  ('story_aisurgeonpilot_2', 'p_ai', 'epic_aisurgeonpilot', 'Story', 'Prompt design & guardrails', '', 'To Do', 'Medium', 5),
  ('task_aisurgeonpilot_2_1', 'p_ai', 'story_aisurgeonpilot_2', 'Task', 'System prompt', '', 'To Do', 'Medium', 2),
  ('task_aisurgeonpilot_2_2', 'p_ai', 'story_aisurgeonpilot_2', 'Task', 'Output moderation', '', 'To Do', 'Medium', 2),
  ('story_aisurgeonpilot_3', 'p_ai', 'epic_aisurgeonpilot', 'Story', 'Workflow orchestration', '', 'To Do', 'Medium', 5),
  ('task_aisurgeonpilot_3_1', 'p_ai', 'story_aisurgeonpilot_3', 'Task', 'Job queue', '', 'To Do', 'Medium', 2),
  ('task_aisurgeonpilot_3_2', 'p_ai', 'story_aisurgeonpilot_3', 'Task', 'Retry policy', '', 'To Do', 'Medium', 2),
  ('epic_claude_code_deepseek_backend', 'p_ai', NULL, 'Epic', 'claude-code-deepseek-backend', 'GitHub: https://github.com/chatgptnotes/claude-code-deepseek-backend — Token-saving toolkit for Claude Code', 'To Do', 'Medium', 21),
  ('story_claude_code_deepseek_backend_1', 'p_ai', 'epic_claude_code_deepseek_backend', 'Story', 'Core CLI / install script', '', 'To Do', 'Medium', 5),
  ('task_claude_code_deepseek_backend_1_1', 'p_ai', 'story_claude_code_deepseek_backend_1', 'Task', 'Bootstrap installer', '', 'To Do', 'Medium', 2),
  ('task_claude_code_deepseek_backend_1_2', 'p_ai', 'story_claude_code_deepseek_backend_1', 'Task', 'Idempotency check', '', 'To Do', 'Medium', 2),
  ('story_claude_code_deepseek_backend_2', 'p_ai', 'epic_claude_code_deepseek_backend', 'Story', 'Configuration & env management', '', 'To Do', 'Medium', 5),
  ('task_claude_code_deepseek_backend_2_1', 'p_ai', 'story_claude_code_deepseek_backend_2', 'Task', 'Config schema', '', 'To Do', 'Medium', 2),
  ('task_claude_code_deepseek_backend_2_2', 'p_ai', 'story_claude_code_deepseek_backend_2', 'Task', '.env template', '', 'To Do', 'Medium', 2),
  ('story_claude_code_deepseek_backend_3', 'p_ai', 'epic_claude_code_deepseek_backend', 'Story', 'Docs & onboarding', '', 'To Do', 'Medium', 5),
  ('task_claude_code_deepseek_backend_3_1', 'p_ai', 'story_claude_code_deepseek_backend_3', 'Task', 'README walkthrough', '', 'To Do', 'Medium', 2),
  ('epic_ironbark', 'p_ai', NULL, 'Epic', 'ironbark', 'GitHub: https://github.com/chatgptnotes/ironbark — Hermes-style learning loop for Claude Code', 'To Do', 'Medium', 21),
  ('story_ironbark_1', 'p_ai', 'epic_ironbark', 'Story', 'Core CLI / install script', '', 'To Do', 'Medium', 5),
  ('task_ironbark_1_1', 'p_ai', 'story_ironbark_1', 'Task', 'Bootstrap installer', '', 'To Do', 'Medium', 2),
  ('task_ironbark_1_2', 'p_ai', 'story_ironbark_1', 'Task', 'Idempotency check', '', 'To Do', 'Medium', 2),
  ('story_ironbark_2', 'p_ai', 'epic_ironbark', 'Story', 'Configuration & env management', '', 'To Do', 'Medium', 5),
  ('task_ironbark_2_1', 'p_ai', 'story_ironbark_2', 'Task', 'Config schema', '', 'To Do', 'Medium', 2),
  ('task_ironbark_2_2', 'p_ai', 'story_ironbark_2', 'Task', '.env template', '', 'To Do', 'Medium', 2),
  ('story_ironbark_3', 'p_ai', 'epic_ironbark', 'Story', 'Docs & onboarding', '', 'To Do', 'Medium', 5),
  ('task_ironbark_3_1', 'p_ai', 'story_ironbark_3', 'Task', 'README walkthrough', '', 'To Do', 'Medium', 2),
  ('epic_claude_model_routing', 'p_ai', NULL, 'Epic', 'claude-model-routing', 'GitHub: https://github.com/chatgptnotes/claude-model-routing — /setup-model-routing slash command', 'To Do', 'Medium', 21),
  ('story_claude_model_routing_1', 'p_ai', 'epic_claude_model_routing', 'Story', 'Core CLI / install script', '', 'To Do', 'Medium', 5),
  ('task_claude_model_routing_1_1', 'p_ai', 'story_claude_model_routing_1', 'Task', 'Bootstrap installer', '', 'To Do', 'Medium', 2),
  ('task_claude_model_routing_1_2', 'p_ai', 'story_claude_model_routing_1', 'Task', 'Idempotency check', '', 'To Do', 'Medium', 2),
  ('story_claude_model_routing_2', 'p_ai', 'epic_claude_model_routing', 'Story', 'Configuration & env management', '', 'To Do', 'Medium', 5),
  ('task_claude_model_routing_2_1', 'p_ai', 'story_claude_model_routing_2', 'Task', 'Config schema', '', 'To Do', 'Medium', 2),
  ('task_claude_model_routing_2_2', 'p_ai', 'story_claude_model_routing_2', 'Task', '.env template', '', 'To Do', 'Medium', 2),
  ('story_claude_model_routing_3', 'p_ai', 'epic_claude_model_routing', 'Story', 'Docs & onboarding', '', 'To Do', 'Medium', 5),
  ('task_claude_model_routing_3_1', 'p_ai', 'story_claude_model_routing_3', 'Task', 'README walkthrough', '', 'To Do', 'Medium', 2),
  ('epic_ai_aas', 'p_ai', NULL, 'Epic', 'AI-aas', 'GitHub: https://github.com/chatgptnotes/AI-aas — Nexaproc AI Gateway', 'To Do', 'Medium', 21),
  ('story_ai_aas_1', 'p_ai', 'epic_ai_aas', 'Story', 'LLM provider integration', '', 'To Do', 'Medium', 5),
  ('task_ai_aas_1_1', 'p_ai', 'story_ai_aas_1', 'Task', 'Anthropic + DeepSeek dual provider', '', 'To Do', 'Medium', 2),
  ('task_ai_aas_1_2', 'p_ai', 'story_ai_aas_1', 'Task', 'Cost monitoring', '', 'To Do', 'Medium', 2),
  ('story_ai_aas_2', 'p_ai', 'epic_ai_aas', 'Story', 'Prompt design & guardrails', '', 'To Do', 'Medium', 5),
  ('task_ai_aas_2_1', 'p_ai', 'story_ai_aas_2', 'Task', 'System prompt', '', 'To Do', 'Medium', 2),
  ('task_ai_aas_2_2', 'p_ai', 'story_ai_aas_2', 'Task', 'Output moderation', '', 'To Do', 'Medium', 2),
  ('story_ai_aas_3', 'p_ai', 'epic_ai_aas', 'Story', 'Workflow orchestration', '', 'To Do', 'Medium', 5),
  ('task_ai_aas_3_1', 'p_ai', 'story_ai_aas_3', 'Task', 'Job queue', '', 'To Do', 'Medium', 2),
  ('task_ai_aas_3_2', 'p_ai', 'story_ai_aas_3', 'Task', 'Retry policy', '', 'To Do', 'Medium', 2),
  ('epic_moving_estimator', 'p_ai', NULL, 'Epic', 'moving-estimator', 'GitHub: https://github.com/chatgptnotes/moving-estimator — Video-based moving size estimator', 'To Do', 'Medium', 21),
  ('story_moving_estimator_1', 'p_ai', 'epic_moving_estimator', 'Story', 'LLM provider integration', '', 'To Do', 'Medium', 5),
  ('task_moving_estimator_1_1', 'p_ai', 'story_moving_estimator_1', 'Task', 'Anthropic + DeepSeek dual provider', '', 'To Do', 'Medium', 2),
  ('task_moving_estimator_1_2', 'p_ai', 'story_moving_estimator_1', 'Task', 'Cost monitoring', '', 'To Do', 'Medium', 2),
  ('story_moving_estimator_2', 'p_ai', 'epic_moving_estimator', 'Story', 'Prompt design & guardrails', '', 'To Do', 'Medium', 5),
  ('task_moving_estimator_2_1', 'p_ai', 'story_moving_estimator_2', 'Task', 'System prompt', '', 'To Do', 'Medium', 2),
  ('task_moving_estimator_2_2', 'p_ai', 'story_moving_estimator_2', 'Task', 'Output moderation', '', 'To Do', 'Medium', 2),
  ('story_moving_estimator_3', 'p_ai', 'epic_moving_estimator', 'Story', 'Workflow orchestration', '', 'To Do', 'Medium', 5),
  ('task_moving_estimator_3_1', 'p_ai', 'story_moving_estimator_3', 'Task', 'Job queue', '', 'To Do', 'Medium', 2),
  ('task_moving_estimator_3_2', 'p_ai', 'story_moving_estimator_3', 'Task', 'Retry policy', '', 'To Do', 'Medium', 2),
  ('epic_zeroriskagent_com', 'p_ai', NULL, 'Epic', 'zeroriskagent.com', 'GitHub: https://github.com/chatgptnotes/zeroriskagent.com — ZeroRisk safety agent', 'To Do', 'Medium', 21),
  ('story_zeroriskagent_com_1', 'p_ai', 'epic_zeroriskagent_com', 'Story', 'LLM provider integration', '', 'To Do', 'Medium', 5),
  ('task_zeroriskagent_com_1_1', 'p_ai', 'story_zeroriskagent_com_1', 'Task', 'Anthropic + DeepSeek dual provider', '', 'To Do', 'Medium', 2),
  ('task_zeroriskagent_com_1_2', 'p_ai', 'story_zeroriskagent_com_1', 'Task', 'Cost monitoring', '', 'To Do', 'Medium', 2),
  ('story_zeroriskagent_com_2', 'p_ai', 'epic_zeroriskagent_com', 'Story', 'Prompt design & guardrails', '', 'To Do', 'Medium', 5),
  ('task_zeroriskagent_com_2_1', 'p_ai', 'story_zeroriskagent_com_2', 'Task', 'System prompt', '', 'To Do', 'Medium', 2),
  ('task_zeroriskagent_com_2_2', 'p_ai', 'story_zeroriskagent_com_2', 'Task', 'Output moderation', '', 'To Do', 'Medium', 2),
  ('story_zeroriskagent_com_3', 'p_ai', 'epic_zeroriskagent_com', 'Story', 'Workflow orchestration', '', 'To Do', 'Medium', 5),
  ('task_zeroriskagent_com_3_1', 'p_ai', 'story_zeroriskagent_com_3', 'Task', 'Job queue', '', 'To Do', 'Medium', 2),
  ('task_zeroriskagent_com_3_2', 'p_ai', 'story_zeroriskagent_com_3', 'Task', 'Retry policy', '', 'To Do', 'Medium', 2),
  ('epic_crm_in_clinics', 'p_crm', NULL, 'Epic', 'crm-in-clinics', 'GitHub: https://github.com/chatgptnotes/crm-in-clinics — Vertical CRM for clinics', 'To Do', 'Medium', 21),
  ('story_crm_in_clinics_1', 'p_crm', 'epic_crm_in_clinics', 'Story', 'Lead capture & enrichment', '', 'To Do', 'Medium', 5),
  ('task_crm_in_clinics_1_1', 'p_crm', 'story_crm_in_clinics_1', 'Task', 'Lead form', '', 'To Do', 'Medium', 2),
  ('task_crm_in_clinics_1_2', 'p_crm', 'story_crm_in_clinics_1', 'Task', 'Enrichment API hook', '', 'To Do', 'Medium', 2),
  ('story_crm_in_clinics_2', 'p_crm', 'epic_crm_in_clinics', 'Story', 'Pipeline / kanban view', '', 'To Do', 'Medium', 5),
  ('task_crm_in_clinics_2_1', 'p_crm', 'story_crm_in_clinics_2', 'Task', 'Drag-drop UI', '', 'To Do', 'Medium', 2),
  ('task_crm_in_clinics_2_2', 'p_crm', 'story_crm_in_clinics_2', 'Task', 'Stage transitions API', '', 'To Do', 'Medium', 2),
  ('story_crm_in_clinics_3', 'p_crm', 'epic_crm_in_clinics', 'Story', 'Email + WhatsApp integration', '', 'To Do', 'Medium', 5),
  ('task_crm_in_clinics_3_1', 'p_crm', 'story_crm_in_clinics_3', 'Task', 'Template engine', '', 'To Do', 'Medium', 2),
  ('task_crm_in_clinics_3_2', 'p_crm', 'story_crm_in_clinics_3', 'Task', 'Send queue', '', 'To Do', 'Medium', 2),
  ('story_crm_in_clinics_4', 'p_crm', 'epic_crm_in_clinics', 'Story', 'Reports & dashboards', '', 'To Do', 'Medium', 5),
  ('task_crm_in_clinics_4_1', 'p_crm', 'story_crm_in_clinics_4', 'Task', 'Funnel report', '', 'To Do', 'Medium', 2),
  ('task_crm_in_clinics_4_2', 'p_crm', 'story_crm_in_clinics_4', 'Task', 'Activity log', '', 'To Do', 'Medium', 2),
  ('story_crm_in_clinics_5', 'p_crm', 'epic_crm_in_clinics', 'Story', 'Multi-tenant isolation', '', 'To Do', 'Medium', 5),
  ('task_crm_in_clinics_5_1', 'p_crm', 'story_crm_in_clinics_5', 'Task', 'Tenant middleware', '', 'To Do', 'Medium', 2),
  ('task_crm_in_clinics_5_2', 'p_crm', 'story_crm_in_clinics_5', 'Task', 'RLS policies', '', 'To Do', 'Medium', 2),
  ('epic_crm_in_electrical', 'p_crm', NULL, 'Epic', 'crm-in-electrical', 'GitHub: https://github.com/chatgptnotes/crm-in-electrical — Vertical CRM for electrical contractors', 'To Do', 'Medium', 21),
  ('story_crm_in_electrical_1', 'p_crm', 'epic_crm_in_electrical', 'Story', 'Lead capture & enrichment', '', 'To Do', 'Medium', 5),
  ('task_crm_in_electrical_1_1', 'p_crm', 'story_crm_in_electrical_1', 'Task', 'Lead form', '', 'To Do', 'Medium', 2),
  ('task_crm_in_electrical_1_2', 'p_crm', 'story_crm_in_electrical_1', 'Task', 'Enrichment API hook', '', 'To Do', 'Medium', 2),
  ('story_crm_in_electrical_2', 'p_crm', 'epic_crm_in_electrical', 'Story', 'Pipeline / kanban view', '', 'To Do', 'Medium', 5),
  ('task_crm_in_electrical_2_1', 'p_crm', 'story_crm_in_electrical_2', 'Task', 'Drag-drop UI', '', 'To Do', 'Medium', 2),
  ('task_crm_in_electrical_2_2', 'p_crm', 'story_crm_in_electrical_2', 'Task', 'Stage transitions API', '', 'To Do', 'Medium', 2),
  ('story_crm_in_electrical_3', 'p_crm', 'epic_crm_in_electrical', 'Story', 'Email + WhatsApp integration', '', 'To Do', 'Medium', 5),
  ('task_crm_in_electrical_3_1', 'p_crm', 'story_crm_in_electrical_3', 'Task', 'Template engine', '', 'To Do', 'Medium', 2),
  ('task_crm_in_electrical_3_2', 'p_crm', 'story_crm_in_electrical_3', 'Task', 'Send queue', '', 'To Do', 'Medium', 2),
  ('story_crm_in_electrical_4', 'p_crm', 'epic_crm_in_electrical', 'Story', 'Reports & dashboards', '', 'To Do', 'Medium', 5),
  ('task_crm_in_electrical_4_1', 'p_crm', 'story_crm_in_electrical_4', 'Task', 'Funnel report', '', 'To Do', 'Medium', 2),
  ('task_crm_in_electrical_4_2', 'p_crm', 'story_crm_in_electrical_4', 'Task', 'Activity log', '', 'To Do', 'Medium', 2),
  ('story_crm_in_electrical_5', 'p_crm', 'epic_crm_in_electrical', 'Story', 'Multi-tenant isolation', '', 'To Do', 'Medium', 5),
  ('task_crm_in_electrical_5_1', 'p_crm', 'story_crm_in_electrical_5', 'Task', 'Tenant middleware', '', 'To Do', 'Medium', 2),
  ('task_crm_in_electrical_5_2', 'p_crm', 'story_crm_in_electrical_5', 'Task', 'RLS policies', '', 'To Do', 'Medium', 2),
  ('epic_crm_in_pharmalabs', 'p_crm', NULL, 'Epic', 'crm-in-pharmalabs', 'GitHub: https://github.com/chatgptnotes/crm-in-pharmalabs — Vertical CRM for pharma labs', 'To Do', 'Medium', 21),
  ('story_crm_in_pharmalabs_1', 'p_crm', 'epic_crm_in_pharmalabs', 'Story', 'Lead capture & enrichment', '', 'To Do', 'Medium', 5),
  ('task_crm_in_pharmalabs_1_1', 'p_crm', 'story_crm_in_pharmalabs_1', 'Task', 'Lead form', '', 'To Do', 'Medium', 2),
  ('task_crm_in_pharmalabs_1_2', 'p_crm', 'story_crm_in_pharmalabs_1', 'Task', 'Enrichment API hook', '', 'To Do', 'Medium', 2),
  ('story_crm_in_pharmalabs_2', 'p_crm', 'epic_crm_in_pharmalabs', 'Story', 'Pipeline / kanban view', '', 'To Do', 'Medium', 5),
  ('task_crm_in_pharmalabs_2_1', 'p_crm', 'story_crm_in_pharmalabs_2', 'Task', 'Drag-drop UI', '', 'To Do', 'Medium', 2),
  ('task_crm_in_pharmalabs_2_2', 'p_crm', 'story_crm_in_pharmalabs_2', 'Task', 'Stage transitions API', '', 'To Do', 'Medium', 2),
  ('story_crm_in_pharmalabs_3', 'p_crm', 'epic_crm_in_pharmalabs', 'Story', 'Email + WhatsApp integration', '', 'To Do', 'Medium', 5),
  ('task_crm_in_pharmalabs_3_1', 'p_crm', 'story_crm_in_pharmalabs_3', 'Task', 'Template engine', '', 'To Do', 'Medium', 2),
  ('task_crm_in_pharmalabs_3_2', 'p_crm', 'story_crm_in_pharmalabs_3', 'Task', 'Send queue', '', 'To Do', 'Medium', 2),
  ('story_crm_in_pharmalabs_4', 'p_crm', 'epic_crm_in_pharmalabs', 'Story', 'Reports & dashboards', '', 'To Do', 'Medium', 5),
  ('task_crm_in_pharmalabs_4_1', 'p_crm', 'story_crm_in_pharmalabs_4', 'Task', 'Funnel report', '', 'To Do', 'Medium', 2),
  ('task_crm_in_pharmalabs_4_2', 'p_crm', 'story_crm_in_pharmalabs_4', 'Task', 'Activity log', '', 'To Do', 'Medium', 2),
  ('story_crm_in_pharmalabs_5', 'p_crm', 'epic_crm_in_pharmalabs', 'Story', 'Multi-tenant isolation', '', 'To Do', 'Medium', 5),
  ('task_crm_in_pharmalabs_5_1', 'p_crm', 'story_crm_in_pharmalabs_5', 'Task', 'Tenant middleware', '', 'To Do', 'Medium', 2),
  ('task_crm_in_pharmalabs_5_2', 'p_crm', 'story_crm_in_pharmalabs_5', 'Task', 'RLS policies', '', 'To Do', 'Medium', 2),
  ('epic_crm_in_manufacturing', 'p_crm', NULL, 'Epic', 'crm-in-manufacturing', 'GitHub: https://github.com/chatgptnotes/crm-in-manufacturing — Vertical CRM for manufacturing', 'To Do', 'Medium', 21),
  ('story_crm_in_manufacturing_1', 'p_crm', 'epic_crm_in_manufacturing', 'Story', 'Lead capture & enrichment', '', 'To Do', 'Medium', 5),
  ('task_crm_in_manufacturing_1_1', 'p_crm', 'story_crm_in_manufacturing_1', 'Task', 'Lead form', '', 'To Do', 'Medium', 2),
  ('task_crm_in_manufacturing_1_2', 'p_crm', 'story_crm_in_manufacturing_1', 'Task', 'Enrichment API hook', '', 'To Do', 'Medium', 2),
  ('story_crm_in_manufacturing_2', 'p_crm', 'epic_crm_in_manufacturing', 'Story', 'Pipeline / kanban view', '', 'To Do', 'Medium', 5),
  ('task_crm_in_manufacturing_2_1', 'p_crm', 'story_crm_in_manufacturing_2', 'Task', 'Drag-drop UI', '', 'To Do', 'Medium', 2),
  ('task_crm_in_manufacturing_2_2', 'p_crm', 'story_crm_in_manufacturing_2', 'Task', 'Stage transitions API', '', 'To Do', 'Medium', 2),
  ('story_crm_in_manufacturing_3', 'p_crm', 'epic_crm_in_manufacturing', 'Story', 'Email + WhatsApp integration', '', 'To Do', 'Medium', 5),
  ('task_crm_in_manufacturing_3_1', 'p_crm', 'story_crm_in_manufacturing_3', 'Task', 'Template engine', '', 'To Do', 'Medium', 2),
  ('task_crm_in_manufacturing_3_2', 'p_crm', 'story_crm_in_manufacturing_3', 'Task', 'Send queue', '', 'To Do', 'Medium', 2),
  ('story_crm_in_manufacturing_4', 'p_crm', 'epic_crm_in_manufacturing', 'Story', 'Reports & dashboards', '', 'To Do', 'Medium', 5),
  ('task_crm_in_manufacturing_4_1', 'p_crm', 'story_crm_in_manufacturing_4', 'Task', 'Funnel report', '', 'To Do', 'Medium', 2),
  ('task_crm_in_manufacturing_4_2', 'p_crm', 'story_crm_in_manufacturing_4', 'Task', 'Activity log', '', 'To Do', 'Medium', 2),
  ('story_crm_in_manufacturing_5', 'p_crm', 'epic_crm_in_manufacturing', 'Story', 'Multi-tenant isolation', '', 'To Do', 'Medium', 5),
  ('task_crm_in_manufacturing_5_1', 'p_crm', 'story_crm_in_manufacturing_5', 'Task', 'Tenant middleware', '', 'To Do', 'Medium', 2),
  ('task_crm_in_manufacturing_5_2', 'p_crm', 'story_crm_in_manufacturing_5', 'Task', 'RLS policies', '', 'To Do', 'Medium', 2),
  ('epic_crm_in_automation', 'p_crm', NULL, 'Epic', 'crm-in-automation', 'GitHub: https://github.com/chatgptnotes/crm-in-automation — Vertical CRM for automation firms', 'To Do', 'Medium', 21),
  ('story_crm_in_automation_1', 'p_crm', 'epic_crm_in_automation', 'Story', 'Lead capture & enrichment', '', 'To Do', 'Medium', 5),
  ('task_crm_in_automation_1_1', 'p_crm', 'story_crm_in_automation_1', 'Task', 'Lead form', '', 'To Do', 'Medium', 2),
  ('task_crm_in_automation_1_2', 'p_crm', 'story_crm_in_automation_1', 'Task', 'Enrichment API hook', '', 'To Do', 'Medium', 2),
  ('story_crm_in_automation_2', 'p_crm', 'epic_crm_in_automation', 'Story', 'Pipeline / kanban view', '', 'To Do', 'Medium', 5),
  ('task_crm_in_automation_2_1', 'p_crm', 'story_crm_in_automation_2', 'Task', 'Drag-drop UI', '', 'To Do', 'Medium', 2),
  ('task_crm_in_automation_2_2', 'p_crm', 'story_crm_in_automation_2', 'Task', 'Stage transitions API', '', 'To Do', 'Medium', 2),
  ('story_crm_in_automation_3', 'p_crm', 'epic_crm_in_automation', 'Story', 'Email + WhatsApp integration', '', 'To Do', 'Medium', 5),
  ('task_crm_in_automation_3_1', 'p_crm', 'story_crm_in_automation_3', 'Task', 'Template engine', '', 'To Do', 'Medium', 2),
  ('task_crm_in_automation_3_2', 'p_crm', 'story_crm_in_automation_3', 'Task', 'Send queue', '', 'To Do', 'Medium', 2),
  ('story_crm_in_automation_4', 'p_crm', 'epic_crm_in_automation', 'Story', 'Reports & dashboards', '', 'To Do', 'Medium', 5),
  ('task_crm_in_automation_4_1', 'p_crm', 'story_crm_in_automation_4', 'Task', 'Funnel report', '', 'To Do', 'Medium', 2),
  ('task_crm_in_automation_4_2', 'p_crm', 'story_crm_in_automation_4', 'Task', 'Activity log', '', 'To Do', 'Medium', 2),
  ('story_crm_in_automation_5', 'p_crm', 'epic_crm_in_automation', 'Story', 'Multi-tenant isolation', '', 'To Do', 'Medium', 5),
  ('task_crm_in_automation_5_1', 'p_crm', 'story_crm_in_automation_5', 'Task', 'Tenant middleware', '', 'To Do', 'Medium', 2),
  ('task_crm_in_automation_5_2', 'p_crm', 'story_crm_in_automation_5', 'Task', 'RLS policies', '', 'To Do', 'Medium', 2),
  ('epic_crm_in_labs', 'p_crm', NULL, 'Epic', 'crm-_in_labs', 'GitHub: https://github.com/chatgptnotes/crm-_in_labs — Vertical CRM for diagnostic labs', 'To Do', 'Medium', 21),
  ('story_crm_in_labs_1', 'p_crm', 'epic_crm_in_labs', 'Story', 'Lead capture & enrichment', '', 'To Do', 'Medium', 5),
  ('task_crm_in_labs_1_1', 'p_crm', 'story_crm_in_labs_1', 'Task', 'Lead form', '', 'To Do', 'Medium', 2),
  ('task_crm_in_labs_1_2', 'p_crm', 'story_crm_in_labs_1', 'Task', 'Enrichment API hook', '', 'To Do', 'Medium', 2),
  ('story_crm_in_labs_2', 'p_crm', 'epic_crm_in_labs', 'Story', 'Pipeline / kanban view', '', 'To Do', 'Medium', 5),
  ('task_crm_in_labs_2_1', 'p_crm', 'story_crm_in_labs_2', 'Task', 'Drag-drop UI', '', 'To Do', 'Medium', 2),
  ('task_crm_in_labs_2_2', 'p_crm', 'story_crm_in_labs_2', 'Task', 'Stage transitions API', '', 'To Do', 'Medium', 2),
  ('story_crm_in_labs_3', 'p_crm', 'epic_crm_in_labs', 'Story', 'Email + WhatsApp integration', '', 'To Do', 'Medium', 5),
  ('task_crm_in_labs_3_1', 'p_crm', 'story_crm_in_labs_3', 'Task', 'Template engine', '', 'To Do', 'Medium', 2),
  ('task_crm_in_labs_3_2', 'p_crm', 'story_crm_in_labs_3', 'Task', 'Send queue', '', 'To Do', 'Medium', 2),
  ('story_crm_in_labs_4', 'p_crm', 'epic_crm_in_labs', 'Story', 'Reports & dashboards', '', 'To Do', 'Medium', 5),
  ('task_crm_in_labs_4_1', 'p_crm', 'story_crm_in_labs_4', 'Task', 'Funnel report', '', 'To Do', 'Medium', 2),
  ('task_crm_in_labs_4_2', 'p_crm', 'story_crm_in_labs_4', 'Task', 'Activity log', '', 'To Do', 'Medium', 2),
  ('story_crm_in_labs_5', 'p_crm', 'epic_crm_in_labs', 'Story', 'Multi-tenant isolation', '', 'To Do', 'Medium', 5),
  ('task_crm_in_labs_5_1', 'p_crm', 'story_crm_in_labs_5', 'Task', 'Tenant middleware', '', 'To Do', 'Medium', 2),
  ('task_crm_in_labs_5_2', 'p_crm', 'story_crm_in_labs_5', 'Task', 'RLS policies', '', 'To Do', 'Medium', 2),
  ('epic_crm_in_aiservices', 'p_crm', NULL, 'Epic', 'crm-in-aiservices', 'GitHub: https://github.com/chatgptnotes/crm-in-aiservices — Vertical CRM for AI services firms', 'To Do', 'Medium', 21),
  ('story_crm_in_aiservices_1', 'p_crm', 'epic_crm_in_aiservices', 'Story', 'Lead capture & enrichment', '', 'To Do', 'Medium', 5),
  ('task_crm_in_aiservices_1_1', 'p_crm', 'story_crm_in_aiservices_1', 'Task', 'Lead form', '', 'To Do', 'Medium', 2),
  ('task_crm_in_aiservices_1_2', 'p_crm', 'story_crm_in_aiservices_1', 'Task', 'Enrichment API hook', '', 'To Do', 'Medium', 2),
  ('story_crm_in_aiservices_2', 'p_crm', 'epic_crm_in_aiservices', 'Story', 'Pipeline / kanban view', '', 'To Do', 'Medium', 5),
  ('task_crm_in_aiservices_2_1', 'p_crm', 'story_crm_in_aiservices_2', 'Task', 'Drag-drop UI', '', 'To Do', 'Medium', 2),
  ('task_crm_in_aiservices_2_2', 'p_crm', 'story_crm_in_aiservices_2', 'Task', 'Stage transitions API', '', 'To Do', 'Medium', 2),
  ('story_crm_in_aiservices_3', 'p_crm', 'epic_crm_in_aiservices', 'Story', 'Email + WhatsApp integration', '', 'To Do', 'Medium', 5),
  ('task_crm_in_aiservices_3_1', 'p_crm', 'story_crm_in_aiservices_3', 'Task', 'Template engine', '', 'To Do', 'Medium', 2),
  ('task_crm_in_aiservices_3_2', 'p_crm', 'story_crm_in_aiservices_3', 'Task', 'Send queue', '', 'To Do', 'Medium', 2),
  ('story_crm_in_aiservices_4', 'p_crm', 'epic_crm_in_aiservices', 'Story', 'Reports & dashboards', '', 'To Do', 'Medium', 5),
  ('task_crm_in_aiservices_4_1', 'p_crm', 'story_crm_in_aiservices_4', 'Task', 'Funnel report', '', 'To Do', 'Medium', 2),
  ('task_crm_in_aiservices_4_2', 'p_crm', 'story_crm_in_aiservices_4', 'Task', 'Activity log', '', 'To Do', 'Medium', 2),
  ('story_crm_in_aiservices_5', 'p_crm', 'epic_crm_in_aiservices', 'Story', 'Multi-tenant isolation', '', 'To Do', 'Medium', 5),
  ('task_crm_in_aiservices_5_1', 'p_crm', 'story_crm_in_aiservices_5', 'Task', 'Tenant middleware', '', 'To Do', 'Medium', 2),
  ('task_crm_in_aiservices_5_2', 'p_crm', 'story_crm_in_aiservices_5', 'Task', 'RLS policies', '', 'To Do', 'Medium', 2),
  ('epic_crm_us', 'p_crm', NULL, 'Epic', 'crm-us', 'GitHub: https://github.com/chatgptnotes/crm-us — CRM regional - US', 'To Do', 'Medium', 21),
  ('story_crm_us_1', 'p_crm', 'epic_crm_us', 'Story', 'Lead capture & enrichment', '', 'To Do', 'Medium', 5),
  ('task_crm_us_1_1', 'p_crm', 'story_crm_us_1', 'Task', 'Lead form', '', 'To Do', 'Medium', 2),
  ('task_crm_us_1_2', 'p_crm', 'story_crm_us_1', 'Task', 'Enrichment API hook', '', 'To Do', 'Medium', 2),
  ('story_crm_us_2', 'p_crm', 'epic_crm_us', 'Story', 'Pipeline / kanban view', '', 'To Do', 'Medium', 5),
  ('task_crm_us_2_1', 'p_crm', 'story_crm_us_2', 'Task', 'Drag-drop UI', '', 'To Do', 'Medium', 2),
  ('task_crm_us_2_2', 'p_crm', 'story_crm_us_2', 'Task', 'Stage transitions API', '', 'To Do', 'Medium', 2),
  ('story_crm_us_3', 'p_crm', 'epic_crm_us', 'Story', 'Email + WhatsApp integration', '', 'To Do', 'Medium', 5),
  ('task_crm_us_3_1', 'p_crm', 'story_crm_us_3', 'Task', 'Template engine', '', 'To Do', 'Medium', 2),
  ('task_crm_us_3_2', 'p_crm', 'story_crm_us_3', 'Task', 'Send queue', '', 'To Do', 'Medium', 2),
  ('story_crm_us_4', 'p_crm', 'epic_crm_us', 'Story', 'Reports & dashboards', '', 'To Do', 'Medium', 5),
  ('task_crm_us_4_1', 'p_crm', 'story_crm_us_4', 'Task', 'Funnel report', '', 'To Do', 'Medium', 2),
  ('task_crm_us_4_2', 'p_crm', 'story_crm_us_4', 'Task', 'Activity log', '', 'To Do', 'Medium', 2),
  ('story_crm_us_5', 'p_crm', 'epic_crm_us', 'Story', 'Multi-tenant isolation', '', 'To Do', 'Medium', 5),
  ('task_crm_us_5_1', 'p_crm', 'story_crm_us_5', 'Task', 'Tenant middleware', '', 'To Do', 'Medium', 2),
  ('task_crm_us_5_2', 'p_crm', 'story_crm_us_5', 'Task', 'RLS policies', '', 'To Do', 'Medium', 2),
  ('epic_crm_uk', 'p_crm', NULL, 'Epic', 'crm-uk', 'GitHub: https://github.com/chatgptnotes/crm-uk — CRM regional - UK', 'To Do', 'Medium', 21),
  ('story_crm_uk_1', 'p_crm', 'epic_crm_uk', 'Story', 'Lead capture & enrichment', '', 'To Do', 'Medium', 5),
  ('task_crm_uk_1_1', 'p_crm', 'story_crm_uk_1', 'Task', 'Lead form', '', 'To Do', 'Medium', 2),
  ('task_crm_uk_1_2', 'p_crm', 'story_crm_uk_1', 'Task', 'Enrichment API hook', '', 'To Do', 'Medium', 2),
  ('story_crm_uk_2', 'p_crm', 'epic_crm_uk', 'Story', 'Pipeline / kanban view', '', 'To Do', 'Medium', 5),
  ('task_crm_uk_2_1', 'p_crm', 'story_crm_uk_2', 'Task', 'Drag-drop UI', '', 'To Do', 'Medium', 2),
  ('task_crm_uk_2_2', 'p_crm', 'story_crm_uk_2', 'Task', 'Stage transitions API', '', 'To Do', 'Medium', 2),
  ('story_crm_uk_3', 'p_crm', 'epic_crm_uk', 'Story', 'Email + WhatsApp integration', '', 'To Do', 'Medium', 5),
  ('task_crm_uk_3_1', 'p_crm', 'story_crm_uk_3', 'Task', 'Template engine', '', 'To Do', 'Medium', 2),
  ('task_crm_uk_3_2', 'p_crm', 'story_crm_uk_3', 'Task', 'Send queue', '', 'To Do', 'Medium', 2),
  ('story_crm_uk_4', 'p_crm', 'epic_crm_uk', 'Story', 'Reports & dashboards', '', 'To Do', 'Medium', 5),
  ('task_crm_uk_4_1', 'p_crm', 'story_crm_uk_4', 'Task', 'Funnel report', '', 'To Do', 'Medium', 2),
  ('task_crm_uk_4_2', 'p_crm', 'story_crm_uk_4', 'Task', 'Activity log', '', 'To Do', 'Medium', 2),
  ('story_crm_uk_5', 'p_crm', 'epic_crm_uk', 'Story', 'Multi-tenant isolation', '', 'To Do', 'Medium', 5),
  ('task_crm_uk_5_1', 'p_crm', 'story_crm_uk_5', 'Task', 'Tenant middleware', '', 'To Do', 'Medium', 2),
  ('task_crm_uk_5_2', 'p_crm', 'story_crm_uk_5', 'Task', 'RLS policies', '', 'To Do', 'Medium', 2),
  ('epic_crm_australia', 'p_crm', NULL, 'Epic', 'crm-australia', 'GitHub: https://github.com/chatgptnotes/crm-australia — CRM regional - Australia', 'To Do', 'Medium', 21),
  ('story_crm_australia_1', 'p_crm', 'epic_crm_australia', 'Story', 'Lead capture & enrichment', '', 'To Do', 'Medium', 5),
  ('task_crm_australia_1_1', 'p_crm', 'story_crm_australia_1', 'Task', 'Lead form', '', 'To Do', 'Medium', 2),
  ('task_crm_australia_1_2', 'p_crm', 'story_crm_australia_1', 'Task', 'Enrichment API hook', '', 'To Do', 'Medium', 2),
  ('story_crm_australia_2', 'p_crm', 'epic_crm_australia', 'Story', 'Pipeline / kanban view', '', 'To Do', 'Medium', 5),
  ('task_crm_australia_2_1', 'p_crm', 'story_crm_australia_2', 'Task', 'Drag-drop UI', '', 'To Do', 'Medium', 2),
  ('task_crm_australia_2_2', 'p_crm', 'story_crm_australia_2', 'Task', 'Stage transitions API', '', 'To Do', 'Medium', 2),
  ('story_crm_australia_3', 'p_crm', 'epic_crm_australia', 'Story', 'Email + WhatsApp integration', '', 'To Do', 'Medium', 5),
  ('task_crm_australia_3_1', 'p_crm', 'story_crm_australia_3', 'Task', 'Template engine', '', 'To Do', 'Medium', 2),
  ('task_crm_australia_3_2', 'p_crm', 'story_crm_australia_3', 'Task', 'Send queue', '', 'To Do', 'Medium', 2),
  ('story_crm_australia_4', 'p_crm', 'epic_crm_australia', 'Story', 'Reports & dashboards', '', 'To Do', 'Medium', 5),
  ('task_crm_australia_4_1', 'p_crm', 'story_crm_australia_4', 'Task', 'Funnel report', '', 'To Do', 'Medium', 2),
  ('task_crm_australia_4_2', 'p_crm', 'story_crm_australia_4', 'Task', 'Activity log', '', 'To Do', 'Medium', 2),
  ('story_crm_australia_5', 'p_crm', 'epic_crm_australia', 'Story', 'Multi-tenant isolation', '', 'To Do', 'Medium', 5),
  ('task_crm_australia_5_1', 'p_crm', 'story_crm_australia_5', 'Task', 'Tenant middleware', '', 'To Do', 'Medium', 2),
  ('task_crm_australia_5_2', 'p_crm', 'story_crm_australia_5', 'Task', 'RLS policies', '', 'To Do', 'Medium', 2),
  ('epic_crm_africa', 'p_crm', NULL, 'Epic', 'crm-africa', 'GitHub: https://github.com/chatgptnotes/crm-africa — CRM regional - Africa', 'To Do', 'Medium', 21),
  ('story_crm_africa_1', 'p_crm', 'epic_crm_africa', 'Story', 'Lead capture & enrichment', '', 'To Do', 'Medium', 5),
  ('task_crm_africa_1_1', 'p_crm', 'story_crm_africa_1', 'Task', 'Lead form', '', 'To Do', 'Medium', 2),
  ('task_crm_africa_1_2', 'p_crm', 'story_crm_africa_1', 'Task', 'Enrichment API hook', '', 'To Do', 'Medium', 2),
  ('story_crm_africa_2', 'p_crm', 'epic_crm_africa', 'Story', 'Pipeline / kanban view', '', 'To Do', 'Medium', 5),
  ('task_crm_africa_2_1', 'p_crm', 'story_crm_africa_2', 'Task', 'Drag-drop UI', '', 'To Do', 'Medium', 2),
  ('task_crm_africa_2_2', 'p_crm', 'story_crm_africa_2', 'Task', 'Stage transitions API', '', 'To Do', 'Medium', 2),
  ('story_crm_africa_3', 'p_crm', 'epic_crm_africa', 'Story', 'Email + WhatsApp integration', '', 'To Do', 'Medium', 5),
  ('task_crm_africa_3_1', 'p_crm', 'story_crm_africa_3', 'Task', 'Template engine', '', 'To Do', 'Medium', 2),
  ('task_crm_africa_3_2', 'p_crm', 'story_crm_africa_3', 'Task', 'Send queue', '', 'To Do', 'Medium', 2),
  ('story_crm_africa_4', 'p_crm', 'epic_crm_africa', 'Story', 'Reports & dashboards', '', 'To Do', 'Medium', 5),
  ('task_crm_africa_4_1', 'p_crm', 'story_crm_africa_4', 'Task', 'Funnel report', '', 'To Do', 'Medium', 2),
  ('task_crm_africa_4_2', 'p_crm', 'story_crm_africa_4', 'Task', 'Activity log', '', 'To Do', 'Medium', 2),
  ('story_crm_africa_5', 'p_crm', 'epic_crm_africa', 'Story', 'Multi-tenant isolation', '', 'To Do', 'Medium', 5),
  ('task_crm_africa_5_1', 'p_crm', 'story_crm_africa_5', 'Task', 'Tenant middleware', '', 'To Do', 'Medium', 2),
  ('task_crm_africa_5_2', 'p_crm', 'story_crm_africa_5', 'Task', 'RLS policies', '', 'To Do', 'Medium', 2),
  ('epic_justdialwork', 'p_crm', NULL, 'Epic', 'justdialwork', 'GitHub: https://github.com/chatgptnotes/justdialwork — Justdial lead management for Hope Hospital', 'To Do', 'Medium', 21),
  ('story_justdialwork_1', 'p_crm', 'epic_justdialwork', 'Story', 'Lead capture & enrichment', '', 'To Do', 'Medium', 5),
  ('task_justdialwork_1_1', 'p_crm', 'story_justdialwork_1', 'Task', 'Lead form', '', 'To Do', 'Medium', 2),
  ('task_justdialwork_1_2', 'p_crm', 'story_justdialwork_1', 'Task', 'Enrichment API hook', '', 'To Do', 'Medium', 2),
  ('story_justdialwork_2', 'p_crm', 'epic_justdialwork', 'Story', 'Pipeline / kanban view', '', 'To Do', 'Medium', 5),
  ('task_justdialwork_2_1', 'p_crm', 'story_justdialwork_2', 'Task', 'Drag-drop UI', '', 'To Do', 'Medium', 2),
  ('task_justdialwork_2_2', 'p_crm', 'story_justdialwork_2', 'Task', 'Stage transitions API', '', 'To Do', 'Medium', 2),
  ('story_justdialwork_3', 'p_crm', 'epic_justdialwork', 'Story', 'Email + WhatsApp integration', '', 'To Do', 'Medium', 5),
  ('task_justdialwork_3_1', 'p_crm', 'story_justdialwork_3', 'Task', 'Template engine', '', 'To Do', 'Medium', 2),
  ('task_justdialwork_3_2', 'p_crm', 'story_justdialwork_3', 'Task', 'Send queue', '', 'To Do', 'Medium', 2),
  ('story_justdialwork_4', 'p_crm', 'epic_justdialwork', 'Story', 'Reports & dashboards', '', 'To Do', 'Medium', 5),
  ('task_justdialwork_4_1', 'p_crm', 'story_justdialwork_4', 'Task', 'Funnel report', '', 'To Do', 'Medium', 2),
  ('task_justdialwork_4_2', 'p_crm', 'story_justdialwork_4', 'Task', 'Activity log', '', 'To Do', 'Medium', 2),
  ('story_justdialwork_5', 'p_crm', 'epic_justdialwork', 'Story', 'Multi-tenant isolation', '', 'To Do', 'Medium', 5),
  ('task_justdialwork_5_1', 'p_crm', 'story_justdialwork_5', 'Task', 'Tenant middleware', '', 'To Do', 'Medium', 2),
  ('task_justdialwork_5_2', 'p_crm', 'story_justdialwork_5', 'Task', 'RLS policies', '', 'To Do', 'Medium', 2),
  ('epic_proposifyai_com', 'p_sales', NULL, 'Epic', 'proposifyai.com', 'GitHub: https://github.com/chatgptnotes/proposifyai.com — ProposifyAI - AI proposal generator', 'To Do', 'Medium', 21),
  ('story_proposifyai_com_1', 'p_sales', 'epic_proposifyai_com', 'Story', 'LLM provider integration', '', 'To Do', 'Medium', 5),
  ('task_proposifyai_com_1_1', 'p_sales', 'story_proposifyai_com_1', 'Task', 'Anthropic + DeepSeek dual provider', '', 'To Do', 'Medium', 2),
  ('task_proposifyai_com_1_2', 'p_sales', 'story_proposifyai_com_1', 'Task', 'Cost monitoring', '', 'To Do', 'Medium', 2),
  ('story_proposifyai_com_2', 'p_sales', 'epic_proposifyai_com', 'Story', 'Prompt design & guardrails', '', 'To Do', 'Medium', 5),
  ('task_proposifyai_com_2_1', 'p_sales', 'story_proposifyai_com_2', 'Task', 'System prompt', '', 'To Do', 'Medium', 2),
  ('task_proposifyai_com_2_2', 'p_sales', 'story_proposifyai_com_2', 'Task', 'Output moderation', '', 'To Do', 'Medium', 2),
  ('story_proposifyai_com_3', 'p_sales', 'epic_proposifyai_com', 'Story', 'Workflow orchestration', '', 'To Do', 'Medium', 5),
  ('task_proposifyai_com_3_1', 'p_sales', 'story_proposifyai_com_3', 'Task', 'Job queue', '', 'To Do', 'Medium', 2),
  ('task_proposifyai_com_3_2', 'p_sales', 'story_proposifyai_com_3', 'Task', 'Retry policy', '', 'To Do', 'Medium', 2),
  ('epic_sterling_tender_gen', 'p_sales', NULL, 'Epic', 'sterling-tender-gen', 'GitHub: https://github.com/chatgptnotes/sterling-tender-gen — Sterling tender document generator', 'To Do', 'Medium', 21),
  ('story_sterling_tender_gen_1', 'p_sales', 'epic_sterling_tender_gen', 'Story', 'LLM provider integration', '', 'To Do', 'Medium', 5),
  ('task_sterling_tender_gen_1_1', 'p_sales', 'story_sterling_tender_gen_1', 'Task', 'Anthropic + DeepSeek dual provider', '', 'To Do', 'Medium', 2),
  ('task_sterling_tender_gen_1_2', 'p_sales', 'story_sterling_tender_gen_1', 'Task', 'Cost monitoring', '', 'To Do', 'Medium', 2),
  ('story_sterling_tender_gen_2', 'p_sales', 'epic_sterling_tender_gen', 'Story', 'Prompt design & guardrails', '', 'To Do', 'Medium', 5),
  ('task_sterling_tender_gen_2_1', 'p_sales', 'story_sterling_tender_gen_2', 'Task', 'System prompt', '', 'To Do', 'Medium', 2),
  ('task_sterling_tender_gen_2_2', 'p_sales', 'story_sterling_tender_gen_2', 'Task', 'Output moderation', '', 'To Do', 'Medium', 2),
  ('story_sterling_tender_gen_3', 'p_sales', 'epic_sterling_tender_gen', 'Story', 'Workflow orchestration', '', 'To Do', 'Medium', 5),
  ('task_sterling_tender_gen_3_1', 'p_sales', 'story_sterling_tender_gen_3', 'Task', 'Job queue', '', 'To Do', 'Medium', 2),
  ('task_sterling_tender_gen_3_2', 'p_sales', 'story_sterling_tender_gen_3', 'Task', 'Retry policy', '', 'To Do', 'Medium', 2),
  ('epic_jotform_dashboard', 'p_sales', NULL, 'Epic', 'jotform-dashboard', 'GitHub: https://github.com/chatgptnotes/jotform-dashboard — JotForm approval-level dashboard', 'To Do', 'Medium', 21),
  ('story_jotform_dashboard_1', 'p_sales', 'epic_jotform_dashboard', 'Story', 'Core CLI / install script', '', 'To Do', 'Medium', 5),
  ('task_jotform_dashboard_1_1', 'p_sales', 'story_jotform_dashboard_1', 'Task', 'Bootstrap installer', '', 'To Do', 'Medium', 2),
  ('task_jotform_dashboard_1_2', 'p_sales', 'story_jotform_dashboard_1', 'Task', 'Idempotency check', '', 'To Do', 'Medium', 2),
  ('story_jotform_dashboard_2', 'p_sales', 'epic_jotform_dashboard', 'Story', 'Configuration & env management', '', 'To Do', 'Medium', 5),
  ('task_jotform_dashboard_2_1', 'p_sales', 'story_jotform_dashboard_2', 'Task', 'Config schema', '', 'To Do', 'Medium', 2),
  ('task_jotform_dashboard_2_2', 'p_sales', 'story_jotform_dashboard_2', 'Task', '.env template', '', 'To Do', 'Medium', 2),
  ('story_jotform_dashboard_3', 'p_sales', 'epic_jotform_dashboard', 'Story', 'Docs & onboarding', '', 'To Do', 'Medium', 5),
  ('task_jotform_dashboard_3_1', 'p_sales', 'story_jotform_dashboard_3', 'Task', 'README walkthrough', '', 'To Do', 'Medium', 2),
  ('epic_myfinancelabagent_com', 'p_sales', NULL, 'Epic', 'MyFinanceLabAgent.com', 'GitHub: https://github.com/chatgptnotes/MyFinanceLabAgent.com — MyFinanceLab AI agent', 'To Do', 'Medium', 21),
  ('story_myfinancelabagent_com_1', 'p_sales', 'epic_myfinancelabagent_com', 'Story', 'LLM provider integration', '', 'To Do', 'Medium', 5),
  ('task_myfinancelabagent_com_1_1', 'p_sales', 'story_myfinancelabagent_com_1', 'Task', 'Anthropic + DeepSeek dual provider', '', 'To Do', 'Medium', 2),
  ('task_myfinancelabagent_com_1_2', 'p_sales', 'story_myfinancelabagent_com_1', 'Task', 'Cost monitoring', '', 'To Do', 'Medium', 2),
  ('story_myfinancelabagent_com_2', 'p_sales', 'epic_myfinancelabagent_com', 'Story', 'Prompt design & guardrails', '', 'To Do', 'Medium', 5),
  ('task_myfinancelabagent_com_2_1', 'p_sales', 'story_myfinancelabagent_com_2', 'Task', 'System prompt', '', 'To Do', 'Medium', 2),
  ('task_myfinancelabagent_com_2_2', 'p_sales', 'story_myfinancelabagent_com_2', 'Task', 'Output moderation', '', 'To Do', 'Medium', 2),
  ('story_myfinancelabagent_com_3', 'p_sales', 'epic_myfinancelabagent_com', 'Story', 'Workflow orchestration', '', 'To Do', 'Medium', 5),
  ('task_myfinancelabagent_com_3_1', 'p_sales', 'story_myfinancelabagent_com_3', 'Task', 'Job queue', '', 'To Do', 'Medium', 2),
  ('task_myfinancelabagent_com_3_2', 'p_sales', 'story_myfinancelabagent_com_3', 'Task', 'Retry policy', '', 'To Do', 'Medium', 2),
  ('epic_bettroi_hisab', 'p_sales', NULL, 'Epic', 'bettroi-hisab', 'GitHub: https://github.com/chatgptnotes/bettroi-hisab — Bettroi Hisab financial tracker', 'To Do', 'Medium', 21),
  ('story_bettroi_hisab_1', 'p_sales', 'epic_bettroi_hisab', 'Story', 'Core CLI / install script', '', 'To Do', 'Medium', 5),
  ('task_bettroi_hisab_1_1', 'p_sales', 'story_bettroi_hisab_1', 'Task', 'Bootstrap installer', '', 'To Do', 'Medium', 2),
  ('task_bettroi_hisab_1_2', 'p_sales', 'story_bettroi_hisab_1', 'Task', 'Idempotency check', '', 'To Do', 'Medium', 2),
  ('story_bettroi_hisab_2', 'p_sales', 'epic_bettroi_hisab', 'Story', 'Configuration & env management', '', 'To Do', 'Medium', 5),
  ('task_bettroi_hisab_2_1', 'p_sales', 'story_bettroi_hisab_2', 'Task', 'Config schema', '', 'To Do', 'Medium', 2),
  ('task_bettroi_hisab_2_2', 'p_sales', 'story_bettroi_hisab_2', 'Task', '.env template', '', 'To Do', 'Medium', 2),
  ('story_bettroi_hisab_3', 'p_sales', 'epic_bettroi_hisab', 'Story', 'Docs & onboarding', '', 'To Do', 'Medium', 5),
  ('task_bettroi_hisab_3_1', 'p_sales', 'story_bettroi_hisab_3', 'Task', 'README walkthrough', '', 'To Do', 'Medium', 2),
  ('epic_visionclawrn', 'p_mobile_other', NULL, 'Epic', 'VisionClawRN', 'GitHub: https://github.com/chatgptnotes/VisionClawRN — VisionClaw RN mobile app', 'To Do', 'Medium', 21),
  ('story_visionclawrn_1', 'p_mobile_other', 'epic_visionclawrn', 'Story', 'Auth flow', '', 'To Do', 'Medium', 5),
  ('task_visionclawrn_1_1', 'p_mobile_other', 'story_visionclawrn_1', 'Task', 'Login screen', '', 'To Do', 'Medium', 2),
  ('task_visionclawrn_1_2', 'p_mobile_other', 'story_visionclawrn_1', 'Task', 'Token refresh', '', 'To Do', 'Medium', 2),
  ('story_visionclawrn_2', 'p_mobile_other', 'epic_visionclawrn', 'Story', 'Offline support', '', 'To Do', 'Medium', 5),
  ('task_visionclawrn_2_1', 'p_mobile_other', 'story_visionclawrn_2', 'Task', 'Local cache', '', 'To Do', 'Medium', 2),
  ('task_visionclawrn_2_2', 'p_mobile_other', 'story_visionclawrn_2', 'Task', 'Sync queue', '', 'To Do', 'Medium', 2),
  ('story_visionclawrn_3', 'p_mobile_other', 'epic_visionclawrn', 'Story', 'Push notifications', '', 'To Do', 'Medium', 5),
  ('task_visionclawrn_3_1', 'p_mobile_other', 'story_visionclawrn_3', 'Task', 'FCM/APNs setup', '', 'To Do', 'Medium', 2),
  ('story_visionclawrn_4', 'p_mobile_other', 'epic_visionclawrn', 'Story', 'App store packaging', '', 'To Do', 'Medium', 5),
  ('task_visionclawrn_4_1', 'p_mobile_other', 'story_visionclawrn_4', 'Task', 'iOS build', '', 'To Do', 'Medium', 2),
  ('task_visionclawrn_4_2', 'p_mobile_other', 'story_visionclawrn_4', 'Task', 'Android build', '', 'To Do', 'Medium', 2),
  ('epic_raftaar', 'p_mobile_other', NULL, 'Epic', 'Raftaar', 'GitHub: https://github.com/chatgptnotes/Raftaar — Raftaar driver app', 'To Do', 'Medium', 21),
  ('story_raftaar_1', 'p_mobile_other', 'epic_raftaar', 'Story', 'Auth flow', '', 'To Do', 'Medium', 5),
  ('task_raftaar_1_1', 'p_mobile_other', 'story_raftaar_1', 'Task', 'Login screen', '', 'To Do', 'Medium', 2),
  ('task_raftaar_1_2', 'p_mobile_other', 'story_raftaar_1', 'Task', 'Token refresh', '', 'To Do', 'Medium', 2),
  ('story_raftaar_2', 'p_mobile_other', 'epic_raftaar', 'Story', 'Offline support', '', 'To Do', 'Medium', 5),
  ('task_raftaar_2_1', 'p_mobile_other', 'story_raftaar_2', 'Task', 'Local cache', '', 'To Do', 'Medium', 2),
  ('task_raftaar_2_2', 'p_mobile_other', 'story_raftaar_2', 'Task', 'Sync queue', '', 'To Do', 'Medium', 2),
  ('story_raftaar_3', 'p_mobile_other', 'epic_raftaar', 'Story', 'Push notifications', '', 'To Do', 'Medium', 5),
  ('task_raftaar_3_1', 'p_mobile_other', 'story_raftaar_3', 'Task', 'FCM/APNs setup', '', 'To Do', 'Medium', 2),
  ('story_raftaar_4', 'p_mobile_other', 'epic_raftaar', 'Story', 'App store packaging', '', 'To Do', 'Medium', 5),
  ('task_raftaar_4_1', 'p_mobile_other', 'story_raftaar_4', 'Task', 'iOS build', '', 'To Do', 'Medium', 2),
  ('task_raftaar_4_2', 'p_mobile_other', 'story_raftaar_4', 'Task', 'Android build', '', 'To Do', 'Medium', 2),
  ('epic_almadamonline', 'p_mobile_other', NULL, 'Epic', 'almadamonline', 'GitHub: https://github.com/chatgptnotes/almadamonline — Al Madam Municipality portal (Sharjah)', 'To Do', 'Medium', 21),
  ('story_almadamonline_1', 'p_mobile_other', 'epic_almadamonline', 'Story', 'Landing page', '', 'To Do', 'Medium', 5),
  ('task_almadamonline_1_1', 'p_mobile_other', 'story_almadamonline_1', 'Task', 'Hero + capability sections', '', 'To Do', 'Medium', 2),
  ('story_almadamonline_2', 'p_mobile_other', 'epic_almadamonline', 'Story', 'SEO & analytics', '', 'To Do', 'Medium', 5),
  ('task_almadamonline_2_1', 'p_mobile_other', 'story_almadamonline_2', 'Task', 'Meta tags', '', 'To Do', 'Medium', 2),
  ('task_almadamonline_2_2', 'p_mobile_other', 'story_almadamonline_2', 'Task', 'GA4 wiring', '', 'To Do', 'Medium', 2),
  ('story_almadamonline_3', 'p_mobile_other', 'epic_almadamonline', 'Story', 'Contact / lead form', '', 'To Do', 'Medium', 5),
  ('task_almadamonline_3_1', 'p_mobile_other', 'story_almadamonline_3', 'Task', 'Form submission handler', '', 'To Do', 'Medium', 2),
  ('epic_indiamonitorapp', 'p_mobile_other', NULL, 'Epic', 'indiamonitorapp', 'GitHub: https://github.com/chatgptnotes/indiamonitorapp — IndiaMonitor real-time intelligence dashboard', 'To Do', 'Medium', 21),
  ('story_indiamonitorapp_1', 'p_mobile_other', 'epic_indiamonitorapp', 'Story', 'LLM provider integration', '', 'To Do', 'Medium', 5),
  ('task_indiamonitorapp_1_1', 'p_mobile_other', 'story_indiamonitorapp_1', 'Task', 'Anthropic + DeepSeek dual provider', '', 'To Do', 'Medium', 2),
  ('task_indiamonitorapp_1_2', 'p_mobile_other', 'story_indiamonitorapp_1', 'Task', 'Cost monitoring', '', 'To Do', 'Medium', 2),
  ('story_indiamonitorapp_2', 'p_mobile_other', 'epic_indiamonitorapp', 'Story', 'Prompt design & guardrails', '', 'To Do', 'Medium', 5),
  ('task_indiamonitorapp_2_1', 'p_mobile_other', 'story_indiamonitorapp_2', 'Task', 'System prompt', '', 'To Do', 'Medium', 2),
  ('task_indiamonitorapp_2_2', 'p_mobile_other', 'story_indiamonitorapp_2', 'Task', 'Output moderation', '', 'To Do', 'Medium', 2),
  ('story_indiamonitorapp_3', 'p_mobile_other', 'epic_indiamonitorapp', 'Story', 'Workflow orchestration', '', 'To Do', 'Medium', 5),
  ('task_indiamonitorapp_3_1', 'p_mobile_other', 'story_indiamonitorapp_3', 'Task', 'Job queue', '', 'To Do', 'Medium', 2),
  ('task_indiamonitorapp_3_2', 'p_mobile_other', 'story_indiamonitorapp_3', 'Task', 'Retry policy', '', 'To Do', 'Medium', 2),
  ('epic_ajmal_perfume', 'p_mobile_other', NULL, 'Epic', 'Ajmal-Perfume', 'GitHub: https://github.com/chatgptnotes/Ajmal-Perfume — Bettroi retail intelligence pitch deck', 'To Do', 'Medium', 21),
  ('story_ajmal_perfume_1', 'p_mobile_other', 'epic_ajmal_perfume', 'Story', 'Landing page', '', 'To Do', 'Medium', 5),
  ('task_ajmal_perfume_1_1', 'p_mobile_other', 'story_ajmal_perfume_1', 'Task', 'Hero + capability sections', '', 'To Do', 'Medium', 2),
  ('story_ajmal_perfume_2', 'p_mobile_other', 'epic_ajmal_perfume', 'Story', 'SEO & analytics', '', 'To Do', 'Medium', 5),
  ('task_ajmal_perfume_2_1', 'p_mobile_other', 'story_ajmal_perfume_2', 'Task', 'Meta tags', '', 'To Do', 'Medium', 2),
  ('task_ajmal_perfume_2_2', 'p_mobile_other', 'story_ajmal_perfume_2', 'Task', 'GA4 wiring', '', 'To Do', 'Medium', 2),
  ('story_ajmal_perfume_3', 'p_mobile_other', 'epic_ajmal_perfume', 'Story', 'Contact / lead form', '', 'To Do', 'Medium', 5),
  ('task_ajmal_perfume_3_1', 'p_mobile_other', 'story_ajmal_perfume_3', 'Task', 'Form submission handler', '', 'To Do', 'Medium', 2),
  ('epic_hopephoenix_in', 'p_mobile_other', NULL, 'Epic', 'hopephoenix.in', 'GitHub: https://github.com/chatgptnotes/hopephoenix.in — HopePhoenix site', 'To Do', 'Medium', 21),
  ('story_hopephoenix_in_1', 'p_mobile_other', 'epic_hopephoenix_in', 'Story', 'Landing page', '', 'To Do', 'Medium', 5),
  ('task_hopephoenix_in_1_1', 'p_mobile_other', 'story_hopephoenix_in_1', 'Task', 'Hero + capability sections', '', 'To Do', 'Medium', 2),
  ('story_hopephoenix_in_2', 'p_mobile_other', 'epic_hopephoenix_in', 'Story', 'SEO & analytics', '', 'To Do', 'Medium', 5),
  ('task_hopephoenix_in_2_1', 'p_mobile_other', 'story_hopephoenix_in_2', 'Task', 'Meta tags', '', 'To Do', 'Medium', 2),
  ('task_hopephoenix_in_2_2', 'p_mobile_other', 'story_hopephoenix_in_2', 'Task', 'GA4 wiring', '', 'To Do', 'Medium', 2),
  ('story_hopephoenix_in_3', 'p_mobile_other', 'epic_hopephoenix_in', 'Story', 'Contact / lead form', '', 'To Do', 'Medium', 5),
  ('task_hopephoenix_in_3_1', 'p_mobile_other', 'story_hopephoenix_in_3', 'Task', 'Form submission handler', '', 'To Do', 'Medium', 2),
  ('epic_linkist_01', 'p_mobile_other', NULL, 'Epic', 'Linkist-01', 'GitHub: https://github.com/chatgptnotes/Linkist-01 — Linkist platform', 'To Do', 'Medium', 21),
  ('story_linkist_01_1', 'p_mobile_other', 'epic_linkist_01', 'Story', 'Core CLI / install script', '', 'To Do', 'Medium', 5),
  ('task_linkist_01_1_1', 'p_mobile_other', 'story_linkist_01_1', 'Task', 'Bootstrap installer', '', 'To Do', 'Medium', 2),
  ('task_linkist_01_1_2', 'p_mobile_other', 'story_linkist_01_1', 'Task', 'Idempotency check', '', 'To Do', 'Medium', 2),
  ('story_linkist_01_2', 'p_mobile_other', 'epic_linkist_01', 'Story', 'Configuration & env management', '', 'To Do', 'Medium', 5),
  ('task_linkist_01_2_1', 'p_mobile_other', 'story_linkist_01_2', 'Task', 'Config schema', '', 'To Do', 'Medium', 2),
  ('task_linkist_01_2_2', 'p_mobile_other', 'story_linkist_01_2', 'Task', '.env template', '', 'To Do', 'Medium', 2),
  ('story_linkist_01_3', 'p_mobile_other', 'epic_linkist_01', 'Story', 'Docs & onboarding', '', 'To Do', 'Medium', 5),
  ('task_linkist_01_3_1', 'p_mobile_other', 'story_linkist_01_3', 'Task', 'README walkthrough', '', 'To Do', 'Medium', 2)
on conflict (id) do nothing;

-- Verify:
--   select project_id, type, count(*) from dev_work_items group by 1, 2 order by 1, 2;
